### ISSUE TITLE
Unity 2021.3.1f1c1版本不支持破解

### ISSUE THREAD

**Issue by zhangsanfenggithub** [tylearymf/UniHacker#1]
![捕获](https://user-images.githubusercontent.com/23573175/166422643-53f0ab58-014a-4cb7-a710-87f000596cf5.PNG)

**Comment by tylearymf** [comment]
c1是国内的特供版，破解不了，要去下载国际版，下载下来是不带 c1的，如果你下载下来还是带c1，建议科学上网，下载地址在这里：[https://unity3d.com/get-unity/download/archive](https://unity3d.com/get-unity/download/archive)

**Comment by zhangsanfenggithub** [comment]
感谢大佬，亲测国际版是可以破解的
