### ISSUE TITLE
[HELP!!] Editor PackageManager can't login

### ISSUE THREAD

**Issue by nNnCoder** [tylearymf/UniHacker#10]
1、can't longin on Package Manager windows panel;
2、on assetstore.unity.com click "open in unity" ,Editor is not response.

**Comment by tylearymf** [comment]
1、将 C:\Program Files\Unity Hub\resources\app.asar.bak 文件改名为 app.asar
2、将 C:\Program Files\Unity Hub\resources\app 文件夹改名为 app~
3、将 C:\ProgramData\Unity\Unity_lic.ulf 文件改名为 Unity_lic.ulf.bak
4、打开 Unity Hub，登录你的账号，添加个人免费许可证，这个时候就可以在商店中下载资源包了。

PS：如果想要还原破解环境可以逆序操作下。

**Comment by nNnCoder** [comment]
thanks~

**Comment by nNnCoder** [comment]
thanks~

**Comment by tylearymf** [comment]
@nNnCoder 新版本支持hub登录了，可以试试
