### ISSUE TITLE
Not working with Unity 2023.1.0a21

### ISSUE THREAD

**Issue by cerrec** [tylearymf/UniHacker#100]
Not working with Unity 2023.1.0a21

**Comment by tylearymf** [comment]
> Not working with Unity 2023.1.0a21

Unity 2022.2.0 and above are not supported

**Comment by cerrec** [comment]
Can you make it work? It would be great.

**Comment by devotionsolutions** [comment]
Do you have plans for 2022.2?

**Comment by tylearymf** [comment]
> Do you have plans for 2022.2?

There is currently no solution.
