### ISSUE TITLE
Apple Silicon 版本编辑器破解以后加入 Hub 时候 Hub 报签名错误

### ISSUE THREAD

**Issue by kxn** [tylearymf/UniHacker#101]
Hub 3.3.0 的

我是改了一下 services/editorManager/editorManager.js 的 addEditor 方法，强制 skipSignatureCheck 解决的

    addEditor(location, skipSignatureCheck) {
        skipSignatureCheck = true;
        return this.validateEditorFile(location, skipSignatureCheck)

可以考虑增加一下。

**Comment by tylearymf** [comment]
> Hub 3.3.0 的
> 
> 我是改了一下 services/editorManager/editorManager.js 的 addEditor 方法，强制 skipSignatureCheck 解决的
> 
> ```
> addEditor(location, skipSignatureCheck) {
>     skipSignatureCheck = true;
>     return this.validateEditorFile(location, skipSignatureCheck)
> ```
> 
> 可以考虑增加一下。

好的

**Comment by tylearymf** [comment]
@kxn 只是增加这一行是吧，其他的应该没变吧
![image](https://user-images.githubusercontent.com/14980389/208009699-04673338-49e3-435d-a648-591d37644a89.png)
