### ISSUE TITLE
Just want to ask about patch

### ISSUE THREAD

**Issue by Backendeng** [tylearymf/UniHacker#102]
Hi,  How are you?

Thank you for your projects.

I want to ask I can use unity without internet using this patch file and unity editor and hub?

I want to use unity 2021.3.11f . Can I patch this version of unity using your project?

hope to your reply.

best regards.

**Comment by tylearymf** [comment]
> Hi, How are you?
> 
> Thank you for your projects.
> 
> I want to ask I can use unity without internet using this patch file and unity editor and hub?
> 
> I want to use unity 2021.3.11f . Can I patch this version of unity using your project?
> 
> hope to your reply.
> 
> best regards.

Yes, you can.

**Comment by Backendeng** [comment]
Thank you for your quick reply.

And I want to ask about unity hub.

Do I download unity hub here::       https://unity.com/download

if yes, is it working for your patch?

or Do i download other unityhub ? if yes,, where?

thank you for your support.

**Comment by tylearymf** [comment]
> Thank you for your quick reply.
> 
> And I want to ask about unity hub.
> 
> Do I download unity hub here:: https://unity.com/download
> 
> if yes, is it working for your patch?
> 
> or Do i download other unityhub ? if yes,, where?
> 
> thank you for your support.

here: https://unity.com/download#how-get-started

**Comment by Backendeng** [comment]
![image](https://user-images.githubusercontent.com/9028177/206887251-d5e3fdf6-cc1a-439f-b3a0-dc9fdf443179.png)

is this right?

**Comment by tylearymf** [comment]
> ![image](https://user-images.githubusercontent.com/9028177/206887251-d5e3fdf6-cc1a-439f-b3a0-dc9fdf443179.png)
> 
> is this right?

Yes.

**Comment by Backendeng** [comment]
Alright.

Thank you for your support. 

Have a nice weekend.
