### ISSUE TITLE
unity 2019.4.37f1和2019.4.40f1无法破解

### ISSUE THREAD

**Issue by altriaAstray** [tylearymf/UniHacker#103]
提示我是国内特供 但是2021.3.15f1和2020.3.42版本可以破解

**Comment by altriaAstray** [comment]
提示我是国内特供  但是2021.3.15f1和2020.3.42版本可以破解

**Comment by tylearymf** [comment]
那就是你下载的有问题咯

**Comment by tylearymf** [comment]
你可以把提示是特供版的，用这个方式下载：Github 国际版下载地址：https://github.com/AlianBlank/download.unity.com

**Comment by altriaAstray** [comment]
好我试试

**Comment by altriaAstray** [comment]
感谢  问题解决了
