### ISSUE TITLE
Does this patcher support for 2022.2.0f1 or above version ?

### ISSUE THREAD

**Issue by raku10dev** [tylearymf/UniHacker#104]
Hello, 
The 2022.2.0f1 version has been released. Does this patcher support for 2022.2.0f1 or above version ?
https://unity.com/releases/editor/whats-new/2022.2.0#release-notes

**Comment by tylearymf** [comment]
#100

**Comment by raku10dev** [comment]
@tylearymf 
Thank you. That's so sad !
