### ISSUE TITLE
mac版本 2019.4.9f1无法破解 显示not support

### ISSUE THREAD

**Issue by seoxiyou** [tylearymf/UniHacker#106]

**Comment by tylearymf** [comment]
提供下Unity二进制文件

**Comment by seoxiyou** [comment]
请问一下二进制文件指的是哪个文件

**Comment by tylearymf** [comment]
在这个目录 Unity.app/Contents/MacOS/ 下的 Unity 文件

**Comment by seoxiyou** [comment]
附件将于2023年1月19日过期
点按以下载
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com.cn%2FB%2FAb7QICprNm_evcD-sOQbqZ4Y42OXAVNHMg-NMg-eerwj05RinV4W5B0S%2F%24%7Bf%7D%3Fo%3DAm-_BRwmFlYLjDx6HO1VjeS8F1ja4ssd8H3xjmUNinxO%26v%3D1%26x%3D3%26a%3DCAogfywpD2rnOP_cUw386zUFx2-qvdNRVTs4_HuWpXQ8lH8SeBDpgJT30jAY6ZCPy9wwIgEAKgkC6AMA_1MVyrRSBBjjY5daBBbkHRJqJiqdYezQfD5mLNQwuPsle1H6bq6R1iHUcUFoeilMm2vmQ4juUP8OcibMR1e7z_RjL-8zAWrIljfFGme6XrKZM2Bw32lQXsjgSF4AoiL_pg%26e%3D1674121037%26fl%3D%26r%3DC5BB35CC-7779-4C9D-8C5F-115B403D084C-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D424D70D3-20A9-4948-A4A1-ACB1552BDE16%26p%3D204%26s%3D_3rze0eT8A5UsDDGpOfQO3a3fd4&uk=USn8u0LWmp5oOiR3IY4KMA&f=Unity&sz=166350832>Unity
166.4 MB

**Comment by tylearymf** [comment]
![image](https://user-images.githubusercontent.com/14980389/208851472-8da388da-9399-40f1-90e0-cdaaba72f361.png)

@seoxiyou 下载不了，你搞个其他网盘吧，例如蓝奏云之类的

**Comment by seoxiyou** [comment]
http://gofile.me/72uz4/FqRroyajK

**Comment by tylearymf** [comment]
@seoxiyou 
https://wwzm.lanzouf.com/iGlFu0ji51la
密码:2g20

**Comment by seoxiyou** [comment]
感谢🙏
