### ISSUE TITLE
Can Unity find out this?

### ISSUE THREAD

**Issue by OverloadedTech** [tylearymf/UniHacker#107]
Hello,

I have found this project some months ago and it was awesome
I am now having a question: If i made a game and i export it (like for Android) and i pubish it on the Stores and let's make that the Unity Team unpacks my APK and checks it. Will they know i have cracked unity?
If they ask me a license i can use an excuse of the account deleted?

Let me know
Thanks

**Comment by tylearymf** [comment]
Unity will know that you are using a cracked version of Unity. Do not use it for publishing. This project is only used to avoid annoying account logins, especially for the **China special edition**. That’s all. If you need to publish a project, please use a legitimate account.

**Comment by OverloadedTech** [comment]
Ok, i think this is all

**Comment by OverloadedTech** [comment]
I have a last question

What can i do then? There is a way to not buy Unity Personal?
If i make more than 100k with Unity Personal and i don't upgrade, what will happen? Thanks

**Comment by tylearymf** [comment]
I don't know, you can ask Unity?

**Comment by OverloadedTech** [comment]
Nope
Thanks anyway
