### ISSUE TITLE
mac版Unity-2021.1.7f1显示不支持

### ISSUE THREAD

**Issue by huaikitty** [tylearymf/UniHacker#108]
相关Unity文件
链接: https://pan.baidu.com/s/1oQS91WzyWlmtzbda2UF-2w?pwd=59vt 提取码: 59vt

**Comment by tylearymf** [comment]
@huaikitty 
https://wwzm.lanzouf.com/iGlFu0ji51la
密码:2g20

**Comment by huaikitty** [comment]
响应迅速,测试无问题.谢谢!
