### ISSUE TITLE
windows 版本 2019.4.40f1(x64) 和 2021.3.0f1(x64) 显示 special edition 无法破解

### ISSUE THREAD

**Issue by pengyj1984** [tylearymf/UniHacker#110]

**Comment by tylearymf** [comment]
只支持国际版，你的是国内版，参考README

**Comment by pengyj1984** [comment]
我都是从 unity.com 上下载的安装包。并且刚才也特地重新安装了一次，确认也都是 f1 的版本，不是 fc1 的版本。但是还是不行。

**Comment by tylearymf** [comment]
> 我都是从 unity.com 上下载的安装包。并且刚才也特地重新安装了一次，确认也都是 f1 的版本，不是 fc1 的版本。但是还是不行。

用这个方式下载：
3. Unity国际版 UnityHub国际版 第三方下载地址（不需要配置代理，基本上下载的都是国际版）
* https://github.com/AlianBlank/download.unity.com

**Comment by pengyj1984** [comment]
嗯，这次可以了。非常感谢。

**Comment by inqb8tr** [comment]
> > 我都是从 unity.com 上下载的安装包。并且刚才也特地重新安装了一次，确认也都是 f1 的版本，不是 fc1 的版本。但是还是不行。
> 
> 用这个方式下载： 3. Unity国际版 UnityHub国际版 第三方下载地址（不需要配置代理，基本上下载的都是国际版）
> 
> * https://github.com/AlianBlank/download.unity.com

你好，我在这个页面下载了4.40还是不可以，是不是hacker的版本不对呢，我试了4.2，4.1，3.6都不行

**Comment by pengyj1984** [comment]
我是从unity.com 上全程开着代理下载的。然后现在下载的是ok的。

**Comment by pengyj1984** [comment]
> > > 我都是从 unity.com 上下载的安装包。并且刚才也特地重新安装了一次，确认也都是 f1 的版本，不是 fc1 的版本。但是还是不行。
> > 
> > 
> > 用这个方式下载： 3. Unity国际版 UnityHub国际版 第三方下载地址（不需要配置代理，基本上下载的都是国际版）
> > 
> > * https://github.com/AlianBlank/download.unity.com
> 
> 你好，我在这个页面下载了4.40还是不可以，是不是hacker的版本不对呢，我试了4.2，4.1，3.6都不行

我是从unity.com 上全程开着代理下载的。然后现在下载的是ok的。

**Comment by inqb8tr** [comment]
> > > > 我都是从 unity.com 上下载的安装包。并且刚才也特地重新安装了一次，确认也都是 f1 的版本，不是 fc1 的版本。但是还是不行。
> > > 
> > > 
> > > 用这个方式下载： 3. Unity国际版 UnityHub国际版 第三方下载地址（不需要配置代理，基本上下载的都是国际版）
> > > 
> > > * https://github.com/AlianBlank/download.unity.com
> > 
> > 
> > 你好，我在这个页面下载了4.40还是不可以，是不是hacker的版本不对呢，我试了4.2，4.1，3.6都不行
> 
> 我是从unity.com 上全程开着代理下载的。然后现在下载的是ok的。

我也用这样方法下载了，终于可以了，万分感谢！！
