### ISSUE TITLE
mac破解后无法验证安装

### ISSUE THREAD

**Issue by SiMaLaoShi** [tylearymf/UniHacker#112]
m1mac，hub版本3.3.0，安装路径都是默认的

**Comment by SiMaLaoShi** [comment]
mac破解安装都是Download failed: Validation Failed

**Comment by tylearymf** [comment]
可能是这个问题 #101 已经修了但是没有发新版，你可以自己试试拉取最新代码build一个看看

**Comment by SiMaLaoShi** [comment]
不太会编mac的

**Comment by tylearymf** [comment]
试下这个版本
https://github.com/tylearymf/UniHacker/releases/tag/4.2
