### ISSUE TITLE
You should join CGpersia

### ISSUE THREAD

**Issue by melnation-com** [tylearymf/UniHacker#114]
https://forum.cgpersia.com/

They're talking about your work here https://forum.cgpersia.com/f13/unipatcher-v2019-win64-182771/index14.html

**Comment by tylearymf** [comment]
I can't register, what are they talking about.

**Comment by melnation-com** [comment]
> CGPersia closed its open registration indefinitely, I can't register, what are they talking about.

Try registering now, before it's too late.
