### ISSUE TITLE
2022.2.4f1 (X64) not support

### ISSUE THREAD

**Issue by BoringMan314** [tylearymf/UniHacker#118]
2022.2.4f1 (X64) not support

**Comment by JCYTop** [comment]
mee too

**Comment by kane9527-e** [comment]
2023.x | 2022.2 | 2022.1 | 2021.x | 2020.x | 2019.x
-- | -- | -- | -- | -- | --
❌ | ❌ | ✔️ | ✔️ | ✔️ | ✔️

**Comment by BoringMan314** [comment]
Sorry, saw it later
