### ISSUE TITLE
不支持 unity_2019.4.40f windows平台

### ISSUE THREAD

**Issue by ntsjun** [tylearymf/UniHacker#124]
确定下载的是国际版本，下载链接：https://beta.unity3d.com/download/ffc62b691db5/Windows64EditorInstaller/UnitySetup64-2019.4.40f1.exe 。
但提示“国内特供版不支持破解”。

**Comment by lanqingruoxi** [comment]
下载时要全程挂梯子， 即使你下了一部分的时候把梯子关了，半路也会重定向到国内的，不是说只要用国外的链接就是国外的，下载完再确认一下你的链接有没有被重定向

**Comment by ntsjun** [comment]
是全程挂梯子，链接是拷贝到浏览器下载完成后任务里的链接。而且安装完成启动时是显示f1，而不是f1c1



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月22日 13:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [tylearymf/UniHacker] 不支持 unity_2019.4.40f windows平台 (Issue #124) |

下载时要全程挂梯子， 即使你下了一部分的时候把梯子关了，半路也会重定向到国内的，不是说只要用国外的链接就是国外的，下载完再确认一下你的链接有没有被重定向

**Comment by lanqingruoxi** [comment]
![image](https://user-images.githubusercontent.com/32923257/220572084-c29b4157-69e2-41eb-b404-5afd0438c880.png)
我测试了一下 是可以破解的

**Comment by ntsjun** [comment]
这就奇怪了。跟电脑上装了很多其他版本的unity有关？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月22日 17:02 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [tylearymf/UniHacker] 不支持 unity_2019.4.40f windows平台 (Issue #124) |


我测试了一下 是可以破解的

**Comment by tylearymf** [comment]
> 这就奇怪了。跟电脑上装了很多其他版本的unity有关？

无关

**Comment by tylearymf** [comment]
@ntsjun 用这个链接下载：https://download.unity3d.com/download_unity/ffc62b691db5/Windows64EditorInstaller/UnitySetup64-2019.4.40f1.exe
