### ISSUE TITLE
Windows系统不支持破解Unity2021.3.19f1

### ISSUE THREAD

**Issue by IkariEren** [tylearymf/UniHacker#125]
UniHackerV4.2不能破解Unity2021.3.19f1，显示“不支持破解”，而不是“国内特供版不支持破解”，希望能尽快支持
![QQ截图20230219154704](https://user-images.githubusercontent.com/106471736/219935702-f52673e7-e243-4fc9-ac8e-916ee6d7f36c.png)

**Comment by tylearymf** [comment]
@IkariEren 看这个，有人提了补丁， https://github.com/tylearymf/UniHacker/issues/122

**Comment by IkariEren** [comment]
好的，感谢

**Comment by IkariEren** [comment]
但是文件没了，麻烦能再提供一下吗，最好是再readme里面，谢谢

**Comment by tylearymf** [comment]
> 但是文件没了，麻烦能再提供一下吗，最好是再readme里面，谢谢

![image](https://user-images.githubusercontent.com/14980389/220112960-f23862bb-99ef-40e2-b2a6-295cafc0e907.png)
照这个编译去修改 UnityPatchInfos，然后运行应该就可以了，我要过几天搞完Mac(M1、Intel)和Windws的再发布个版本，现在暂时不发布呢

**Comment by IkariEren** [comment]
好的，谢谢
