### ISSUE TITLE
Unity 2021.3.19f1 dont support

### ISSUE THREAD

**Issue by Unagaml** [tylearymf/UniHacker#127]
Hello everyone. I wanted to hack unity 2021 but he writes that this version is not supported. Add support for this version please. Thank you in advance)
System: Windows 11

![Снимок экрана 2023-02-21 232158](https://user-images.githubusercontent.com/92244180/220450932-78899cee-8b3d-4a47-91e7-72851f3551a9.png)

**Comment by tylearymf** [comment]
See this. https://github.com/tylearymf/UniHacker/issues/122
