### ISSUE TITLE
2021.3.19f1 (X64)国际版显示不支持

### ISSUE THREAD

**Issue by sunsvip** [tylearymf/UniHacker#129]
难道新发布的2021.3.19f1也重构了License逻辑？这么牛批的开源项目千万别凉啊，巨佬还有计划更新吗？

**Comment by tylearymf** [comment]
> 难道新发布的2021.3.19f1也重构了License逻辑？这么牛批的开源项目千万别凉啊，巨佬还有计划更新吗？

这个版本的过几天发布，最近还没空

**Comment by sunsvip** [comment]
> 这个版本的过几天发布，最近还没空
感谢，临时用 #122 里的方法成功了

**Comment by sunsvip** [comment]
#122
