### ISSUE TITLE
支持linux 2020.3.33f1

### ISSUE THREAD

**Issue by eelgame** [tylearymf/UniHacker#13]

**Comment by tylearymf** [comment]
发下对应的Unity二进制文件，官网好像没有提供对应的下载

**Comment by eelgame** [comment]
https://github.com/eelgame/UniHacker/raw/main/linux/Unity-2020.3.33f1

**Comment by eelgame** [comment]
如果可以的话，希望能提供下找pattern的方法，谢谢。eelgame@qq.com

**Comment by tylearymf** [comment]
已发
