### ISSUE TITLE
2020.3.45 is no longer patchable, working signatures provided

### ISSUE THREAD

**Issue by BluBb-mADe** [tylearymf/UniHacker#130]
I don't know why the patch in UniHacker stopped working but here is what I have found that works for the windows 2020.3 version family.

First, after this signature `48 8d 4d 28 E8 ?? ?? ??  FE 90 48 8D 4D B8 E8 ?? ?? ?? FE 90` I replace  `0F B6 C3` with `B0 01 90` effectively just patching the return value to true with `MOV AL 1`.
In more recent versions I found I also needed a second patch for the licensing code to even reach the legacy branch.
In the initialization of the licensing module UnityConnect gets called and previously, because I just removed/renamed the entire `Data\Resources\Licensing` folder, this would just return a nullptr. But in more recent versions it started to return something else which prevents the legacy code from executing.
By replacing the jump after `A1 64 00 00 33 FF 40 84 F6` (not sure how generic this signature is) in 2020.3.45 `0F 84` with `90 E9` (conditional to unconditional JMP) the legacy branch will always be reached regardless of the return value.

I hope this might be useful to someone.

**Comment by mkfcga** [comment]
hi. I've problem with 3.45 too. .
can you just build your modified version for community?
tanks btw

**Comment by BluBb-mADe** [comment]
I stopped maintaining my own script after I found this awesome project but I updated it to at least be able to patch this one version for myself until an update comes out that fixes UniHacker.
I uploaded it here https://gist.github.com/BluBb-mADe/b0216911fe295dd24b566940b12cf094
It's just a python script which requires a fairly new python version. Hope I could help.

**Comment by mkfcga** [comment]
it worked!
I wish you at least 7 more extra beautiful days.
you saved my days..
regards.
