### ISSUE TITLE
2021.3.19f1 破解后创建不了项目

### ISSUE THREAD

**Issue by ZkiKz** [tylearymf/UniHacker#131]
tamp":"2023-02-24T01:52:18.985Z","level":"info","moduleName":"CloudAnalytics","message":"[\n  AxiosError: connect ETIMEDOUT 119.28.40.105:443\n      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {\n    port: 443,\n    address: '119.28.40.105',\n    syscall: 'connect',\n    code: 'ETIMEDOUT',\n    errno: -4039,\n    config: {\n      transitional: [Object],\n      adapter: [Function: httpAdapter],\n      transformRequest: [Array],\n      transformResponse: [Array],\n      timeout: 0,\n      xsrfCookieName: 'XSRF-TOKEN',\n      xsrfHeaderName: 'X-XSRF-TOKEN',\n      maxContentLength: -1,\n      maxBodyLength: -1,\n      env: [Object],\n      validateStatus: [Function: validateStatus],\n      headers: [Object],\n      proxy: false,\n      responseType: 'json',\n      method: 'post',\n      url: 'https://prd-lender.cdp.internal.unity3d.com/v1/events',\n      data: '{\"common\":{\"appid\":\"hub\",\"hub_version\":\"3.4.1-g\",\"machineid\":\"HYpMoFOOM4TWSzIFEsGlhgBuP+o=\",\"platform\":\"kWindows\",\"platformid\":7,\"session_guid\":\"be6452a0-b3e2-11ed-94cc-5ff5202dbbbd\",\"cloud_user_id\":\"anonymous\",\"license_hash\":\"5259e76fe25752358a6c2ce6a2b689e717a76afd\"}}\\n' +\n        '{\"type\":\"hub.start.v1\",\"msg\":{\"mode\":\"HUB UI\",\"ts\":1677202196094}}\\n'\n    },\n    request: Writable {\n      _writableState: [WritableState],\n      _events: [Object: null prototype],\n      _eventsCount: 3,\n      _maxListeners: undefined,\n      _options: [Object],\n      _ended: false,\n      _ending: true,\n      _redirectCount: 0,\n      _redirects: [],\n      _requestBodyLength: 338,\n      _requestBodyBuffers: [Array],\n      _onNativeResponse: [Function (anonymous)],\n      _currentRequest: [ClientRequest],\n      _currentUrl: 'https://prd-lender.cdp.internal.unity3d.com/v1/events',\n      [Symbol(kCapture)]: false\n    }\n  }\n]"}
{"timestamp":"2023-02-24T01:52:57.930Z","level":"info","moduleName":"LicensingSdkService","message":"[ 'Get all entitlement groups' ]"}
{"timestamp":"2023-02-24T01:52:57.950Z","level":"info","moduleName":"LicensingSdkService","message":"[ 'Successfully received all entitlement groups details' ]"}
{"timestamp":"2023-02-24T01:52:57.950Z","level":"info","moduleName":"LicensingSdkService","message":"[ 'Received 1 entitlement groups' ]"}
{"timestamp":"2023-02-24T01:53:14.976Z","level":"info","moduleName":"LicensingSdkService","message":"[ 'checkEntitlements: checking entitlements for: com.unity.editor.ui' ]"}
{"timestamp":"2023-02-24T01:53:14.988Z","level":"info","moduleName":"LicensingSdkService","message":"[ 'Successfully checked for entitlements request.' ]"}
{"timestamp":"2023-02-24T01:53:14.990Z","level":"info","moduleName":"LicensingSdkService","message":"[ 'Get all entitlement groups' ]"}
{"timestamp":"2023-02-24T01:53:14.990Z","level":"error","moduleName":"LocalProjectService","message":"[\n  'Error while opening a local new project: ',\n  ProjectError\n      at ProjectValidatorService.<anonymous> (D:\\Program Files\\Unity Hub\\resources\\app.asar\\build\\main\\services\\projectService\\ProjectValidatorService.js:51:23)\n      at Generator.next (<anonymous>)\n      at fulfilled (D:\\Program Files\\Unity Hub\\resources\\app.asar\\build\\main\\services\\projectService\\ProjectValidatorService.js:5:58) {\n    errorCode: 'ERROR.PROJECT.PATH_NOT_FOUND',\n    projectName: undefined,\n    projectVersion: undefined,\n    projectArchitecture: undefined,\n    projectPath: undefined\n  }\n]"}
{"timestamp":"2023-02-24T01:53:14.990Z","level":"error","moduleName":"LocalProjectService","message":"[\n  'Error while opening project: {\"code\":400,\"error\":{\"errorCode\":\"ERROR.PROJECT.PATH_NOT_FOUND\",\"projectName\":\"TestHack\",\"projectVersion\":\"2021.3.19f1\",\"projectArchitecture\":\"x86_64\",\"projectPath\":\"D:\\\\\\\\UnityWork\\\\\\\\TestHack\"}}'\n]"}
{"timestamp":"2023-02-24T01:53:15.010Z","level":"info","moduleName":"LicensingSdkService","message":"[ 'Successfully received all entitlement groups details' ]"}
{"timestamp":"2023-02-24T01:53:15.010Z","level":"info","moduleName":"LicensingSdkService","message":"[ 'Received 1 entitlement groups' ]"}
{"timestamp":"2023-02-24T01:53:15.010Z","level":"info","moduleName":"LicensingSdkService","message":"[ 'Get all entitlement groups' ]"}
{"timestamp":"2023-02-24T01:53:15.025Z","level":"info","moduleName":"LicensingSdkService","message":"[ 'Successfully received all entitlement groups details' ]"}
{"timestamp":"2023-02-24T01:53:15.025Z","level":"info","moduleName":"LicensingSdkService","message":"[ 'Received 1 entitlement groups' ]"}
{"timestamp":"2023-02-24T01:53:19.003Z","level":"info","moduleName":"CloudAnalytics","message":"[\n  AxiosError: connect ETIMEDOUT 119.28.40.105:443\n      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {\n    port: 443,\n    address: '119.28.40.105',\n    syscall: 'connect',\n    code: 'ETIMEDOUT',\n    errno: -4039,\n    config: {\n      transitional: [Object],\n      adapter: [Function: httpAdapter],\n      transformRequest: [Array],\n      transformResponse: [Array],\n      timeout: 0,\n      xsrfCookieName: 'XSRF-TOKEN',\n      xsrfHeaderName: 'X-XSRF-TOKEN',\n      maxContentLength: -1,\n      maxBodyLength: -1,\n      env: [Object],\n      validateStatus: [Function: validateStatus],\n      headers: [Object],\n      proxy: false,\n      responseType: 'json',\n      method: 'post',\n      url: 'https://prd-lender.cdp.internal.unity3d.com/v1/events',\n      data: '{\"common\":{\"appid\":\"hub\",\"hub_version\":\"3.4.1-g\",\"machineid\":\"HYpMoFOOM4TWSzIFEsGlhgBuP+o=\",\"platform\":\"kWindows\",\"platformid\":7,\"session_guid\":\"be6452a0-b3e2-11ed-94cc-5ff5202dbbbd\",\"cloud_user_id\":\"anonymous\",\"license_hash\":\"5259e76fe25752358a6c2ce6a2b689e717a76afd\"}}\\n' +\n        '{\"type\":\"hub.start.v1\",\"msg\":{\"mode\":\"HUB UI\",\"ts\":1677202196094}}\\n'\n    },\n    request: Writable {\n      _writableState: [WritableState],\n      _events: [Object: null prototype],\n      _eventsCount: 3,\n      _maxListeners: undefined,\n      _options: [Object],\n      _ended: false,\n      _ending: true,\n      _redirectCount: 0,\n      _redirects: [],\n      _requestBodyLength: 338,\n      _requestBodyBuffers: [Array],\n      _onNativeResponse: [Function (anonymous)],\n      _currentRequest: [ClientRequest],\n      _currentUrl: 'https://prd-lender.cdp.internal.unity3d.com/v1/events',\n      [Symbol(kCapture)]: false\n    }\n  }\n]"}

**Comment by tylearymf** [comment]
你的是啥平台，第一次打开需要等几分钟
