### ISSUE TITLE
Unity2020.3.45破解成功启动不了

### ISSUE THREAD

**Issue by xuxiaomao2018** [tylearymf/UniHacker#132]
Unity2020.3.45破解成功启动不了

**Comment by TianJingDa** [comment]
2020.3.45f1，破解成功启动不了，通过hub打开工程后，一直在转圈
2019.4.18f1，破解成功后可以启动

**Comment by tylearymf** [comment]
https://drive.google.com/file/d/154RwBI53Pii8Of_J1IHP7xnw9XiaA8bS/view?usp=sharing
