### ISSUE TITLE
sign in时没有弹出任何信息，这是log日志，请问是什么问题、

### ISSUE THREAD

**Issue by wujiaze** [tylearymf/UniHacker#135]
{"timestamp":"2023-02-27T11:36:04.069Z","level":"info","moduleName":"Authentification Service","message":"[ 'Fetching user info from the identity provider using access token' ]"}
{"timestamp":"2023-02-27T11:36:04.070Z","level":"error","moduleName":"Authentification Service","message":"[\n  \"Error fetching user info from Access Token: TypeError: Cannot read property 'expiration' of null\"\n]"}
{"timestamp":"2023-02-27T11:36:04.070Z","level":"error","moduleName":"FeatureFlagsService","message":"[\n  'Invalid user specified. Please see https://docs.launchdarkly.com/docs/js-sdk-reference#initializing-the-client for instructions on SDK initialization.'\n]"}
{"timestamp":"2023-02-27T11:36:04.071Z","level":"error","moduleName":"FeatureFlagsService","message":"[\n  'Problem identifying user',\n  t [LaunchDarklyInvalidUserError]: Invalid user specified. Please see https://docs.launchdarkly.com/docs/js-sdk-reference#initializing-the-client for instructions on SDK initialization.\n      at Object.UserValidator.e.validateUser (C:\\Program Files\\Unity Hub\\resources\\app\\node_modules\\launchdarkly-js-sdk-common\\dist\\ldclient-common.cjs.js:1:23696)\n      at C:\\Program Files\\Unity Hub\\resources\\app\\node_modules\\launchdarkly-js-sdk-common\\dist\\ldclient-common.cjs.js:1:35527\n      at processTicksAndRejections (internal/process/task_queues.js:93:5) {\n    code: undefined\n  }\n]"}
{"timestamp":"2023-02-27T11:36:04.071Z","level":"info","moduleName":"FeatureFlagsService","message":"[ 'Set identity to', undefined ]"}
{"timestamp":"2023-02-27T11:36:04.071Z","level":"error","message":"Unhandled promise rejection, reason: Cannot read property 'expiration' of null\n\tstack TypeError: Cannot read property 'expiration' of null\n    at Object.monitorTokens (C:\\Program Files\\Unity Hub\\resources\\app\\build\\main\\services\\authService\\AuthService.js:278:50)\n    at Object.<anonymous> (C:\\Program Files\\Unity Hub\\resources\\app\\build\\main\\services\\authService\\AuthService.js:193:22)\n    at Generator.next (<anonymous>)\n    at C:\\Program Files\\Unity Hub\\resources\\app\\build\\main\\services\\authService\\AuthService.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Program Files\\Unity Hub\\resources\\app\\build\\main\\services\\authService\\AuthService.js:4:12)\n    at Object.logInWithAccessToken (C:\\Program Files\\Unity Hub\\resources\\app\\build\\main\\services\\authService\\AuthService.js:187:16)\n    at Object.openSignIn (C:\\Program Files\\Unity Hub\\resources\\app\\build\\main\\services\\authService\\AuthService.js:165:14)\n    at C:\\Program Files\\Unity Hub\\resources\\app\\build\\main\\ipcMain\\IpcMainService.js:15:65\n    at electron/js2c/browser_init.js:197:579"}

**Comment by tylearymf** [comment]
#133
