### ISSUE TITLE
2021 3.15F

### ISSUE THREAD

**Issue by hansenchen2015** [tylearymf/UniHacker#136]
2021 3.15 无法破解
![image](https://user-images.githubusercontent.com/101965137/222071355-1bb0349c-640f-49aa-8282-9d986276de94.png)

**Comment by hansenchen2015** [comment]
下载地址   https://www.aliyundrive.com/s/7pmPTa6PXW6

**Comment by tylearymf** [comment]
@hansenchen2015 Unity二进制文件在 你的Unity安装后的目录/Editor/Unity.exe，把Unity.exe发我就可以了，不要发整个安装包。。

**Comment by hansenchen2015** [comment]
好的， 已重新上传   https://www.aliyundrive.com/s/8aNFmn6HM6E

**Comment by dickredone** [comment]
我试了一下，4.2版本可以成功破解

**Comment by hansenchen2015** [comment]
确实，4.2可以。我先使用试试。感谢
