### ISSUE TITLE
2021.3.15f1 V4.3 显示不支持破解 V4.2可以破解 国际版不是中国特供版

### ISSUE THREAD

**Issue by FForever0606** [tylearymf/UniHacker#142]
![QQ截图20230304122952](https://user-images.githubusercontent.com/69239189/222875708-fb0f3777-cfdc-47d9-b06c-516108296d10.png)
![QQ截图20230304123631](https://user-images.githubusercontent.com/69239189/222875933-1f632482-9ed9-43b9-b060-7a91f3559826.png)

**Comment by tylearymf** [comment]
嗯，4.3版本有问题
