### ISSUE TITLE
Unity 2020.3.45f1

### ISSUE THREAD

**Issue by Hafiz-Abdul-Majid-Waseer** [tylearymf/UniHacker#146]
Patch is applied but if won't opens the editor?
![Capture](https://user-images.githubusercontent.com/20488932/223656246-f02af81b-a4e6-41bc-ad64-a8e1802f2a28.PNG)
![Capture2](https://user-images.githubusercontent.com/20488932/223656314-2e39eddf-eb8e-4ed1-abe5-cfb63a533751.PNG)

**Comment by tylearymf** [comment]
https://drive.google.com/file/d/154RwBI53Pii8Of_J1IHP7xnw9XiaA8bS/view?usp=sharing
