### ISSUE TITLE
Unity2020.3.45f1 不支持

### ISSUE THREAD

**Issue by Polaris95Aspire** [tylearymf/UniHacker#148]
今天刚测试了一下，目前LTS版本Unity2021.3.20f1通过，Unity2020.3.45f1 不支持

**Comment by tylearymf** [comment]
嗯，还没发新版，可以用这个或者自己本地构建
https://drive.google.com/file/d/154RwBI53Pii8Of_J1IHP7xnw9XiaA8bS/view?usp=sharing
