### ISSUE TITLE
UniHacker 4.4 破解失败

### ISSUE THREAD

**Issue by hsl9999** [tylearymf/UniHacker#149]
随便新建空工程，闪屏阶段过不去，一直是黑屏阶段。Unity 2020.3.45

**Comment by tylearymf** [comment]
mac?

**Comment by hsl9999** [comment]
> 

windows

**Comment by tylearymf** [comment]
![image](https://user-images.githubusercontent.com/14980389/224599189-f2a79ce7-57ad-4759-bb43-5421aae2c9da.png)
我这边是可以进的，你是不是unity或者hub有问题

**Comment by hsl9999** [comment]
可以进，但是打成安卓包后闪屏过不去一直黑屏，就是一个空工程。我看了其它版本是可以正常切换过去的。而且换成未破解就可以

**Comment by hsl9999** [comment]
我又重新破解试了下，2019.4.40没问题，2020.4.43~2020.4.45不行。其它版本没试。都是windows。

**Comment by tylearymf** [comment]
> 我又重新破解试了下，2019.4.40没问题，2020.4.43~2020.4.45不行。其它版本没试。都是windows。

我试了下windows的2020.3.45的mono，打出来的包可以进，il2cpp的没试，你打的是哪种

**Comment by hsl9999** [comment]
il2cpp

**Comment by hsl9999** [comment]
> > 我又重新破解试了下，2019.4.40没问题，2020.4.43~2020.4.45不行。其它版本没试。都是windows。
> 
> 我试了下windows的2020.3.45的mono，打出来的包可以进，il2cpp的没试，你打的是哪种

2019.4.38~39也试了下，应该是2019的都没问题

**Comment by hsl9999** [comment]
> > 我又重新破解试了下，2019.4.40没问题，2020.4.43~2020.4.45不行。其它版本没试。都是windows。
> 
> 我试了下windows的2020.3.45的mono，打出来的包可以进，il2cpp的没试，你打的是哪种

2019.4.38~39也试了下，应该是2019的都没问题

**Comment by hsl9999** [comment]
> 

不用查了，模拟器问题，设备是OK的

**Comment by tylearymf** [comment]
@hsl9999 是哪个模拟器，让我避避坑

**Comment by hsl9999** [comment]
> @hsl9999 是哪个模拟器，让我避避坑

bluestack
