### ISSUE TITLE
2019.4.29f1  不支持破解

### ISSUE THREAD

**Issue by hlfl1l1** [tylearymf/UniHacker#15]
2019.4.29f1  不支持破解

**Comment by tylearymf** [comment]
提供下对应的Unity二进制文件

**Comment by tylearymf** [comment]
![image](https://user-images.githubusercontent.com/14980389/173607275-51acef99-fb2a-44d1-b086-3898e70f384d.png)
![image](https://user-images.githubusercontent.com/14980389/173607381-92e9184a-e1e6-4deb-a49b-c2e58e091036.png)
