### ISSUE TITLE
Mac m1 2019.4.15f1 Not Support Patch

### ISSUE THREAD

**Issue by fjqzlqh** [tylearymf/UniHacker#152]
4.3 4.2 都无法破解，二进制地址：
https://www.aliyundrive.com/s/uoD74EPYUug

**Comment by fjqzlqh** [comment]
添加以下代码然后自己编译即可
            new()
            {
                // 2019.4.15
                Version = "2019.4.15",
                LightPattern = ToBytes(ToArray("FF 80 B8 69 4C 00 00 00 74 5D 48 8D 35 90"), ToArray("45 84 E4 0F 84 3E 02 00 00 48 8D B5 30")),
                DarkPattern = ToBytes(ToArray("FF 80 B8 69 4C 00 00 00 EB 5D 48 8D 35 90"), ToArray("45 84 E4 0F 85 3E 02 00 00 48 8D B5 30")),
            },

**Comment by damodao** [comment]
请问这个码是怎么来的
