### ISSUE TITLE
关于破解后从asset store导入asset

### ISSUE THREAD

**Issue by DokiYoloo** [tylearymf/UniHacker#166]
你好，我想问下

asset store里的素材在2022.1的版本里不支持在ide里直接导入了
需要登陆到自己的unity账号才行

但是我发现在破解后（也可能不是破解原因） 我从 package manage 选择到my assets窗口点击 sign in 按钮
好像没有反应

不确定是否是因为破解补丁原因 可否给个提示

**Comment by tylearymf** [comment]
看README
