### ISSUE TITLE
建议修改xattr 至 /usr/bin/xattr

### ISSUE THREAD

**Issue by oslo254804746** [tylearymf/UniHacker#173]
如果brew 里有`xattr` 可能会导致破解失败
<img width="847" alt="image" src="https://user-images.githubusercontent.com/57609491/232748974-7c51df95-a4b5-4352-8d91-837d67dace55.png">
重新选择需要破解的`Unity` 会显示已破解，但是其实是没有破解的, 点击还原后这个`Unity.app`就无法使用了

<img width="291" alt="image" src="https://user-images.githubusercontent.com/57609491/232749369-dfc3a25c-dcd7-40f3-8279-c11bffd4f73a.png">

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/57609491/232749417-c4257092-5b10-4456-a422-7c148651b89c.png">

直接指定全路径基本上不会出问题

**Comment by tylearymf** [comment]
好的，谢谢反馈
