### ISSUE TITLE
UnityHub3.4.2.0 (X64) windows破解完,打开奔溃

### ISSUE THREAD

**Issue by shuimoyer** [tylearymf/UniHacker#176]

**Comment by Hafiz-Abdul-Majid-Waseer** [comment]
unfortunately, I unintentionally updated to **3.4.2**, now i can't create a new project until a new patch arrives :)

**Comment by hungpqz** [comment]
How to roll back to 3.4.1?

**Comment by tylearymf** [comment]
破解hub时执行下面选项：需要登录账号➕关闭自动更新。

To crack the hub, execute the following options: login to your account + turn off automatic updates.

**Comment by hungpqz** [comment]
I dit it, but when I run the hub it says: No active licenses To create and open projects, you need an active license. Then I dont even add personal license to the hub

**Comment by tylearymf** [comment]
试下新版本
