### ISSUE TITLE
2019.4.40f1 can't be cracked on windows

### ISSUE THREAD

**Issue by koemanqiu** [tylearymf/UniHacker#177]
2019.4.40f1 can't be cracked on windows

**Comment by Prosopho** [comment]
> 2019.4.40f1 can't be cracked on windows

You can. What's your used unihacker version?

**Comment by koemanqiu** [comment]
4.5

**Comment by koemanqiu** [comment]
By deleting the floder (Editor\Data\Resources\Licensing), cracked successfully
