### ISSUE TITLE
2021.3.4f1 (X64) 不支持破解

### ISSUE THREAD

**Issue by BenderWhite** [tylearymf/UniHacker#18]
![image](https://user-images.githubusercontent.com/107112144/172591995-d63716d1-2b34-42ff-b299-50e006069f2e.png)
https://drive.google.com/file/d/1r71-EJtb8iT4GwXVNlFmn-ZYtuU15wbN/view?usp=sharing
是科学上网，直接在UnityHUB中下载安装的

**Comment by tylearymf** [comment]
更新
