### ISSUE TITLE
是否可以支持将授权改为 Personal版本？

### ISSUE THREAD

**Issue by liangddyy** [tylearymf/UniHacker#197]
为什么不登录账号？
登录太麻烦了，经常需要重新获得授权。所以用这个。
但是有些付费工具，如果Unity是 Pro的授权，需要购买商业授权。

**Comment by tylearymf** [comment]
你可以试着将之前的featureID去掉，添加以下featureID试试，在Unity_lic.ulf中

<Features>
        <Feature Value="33"/>
        <Feature Value="1"/>
        <Feature Value="12"/>
        <Feature Value="2"/>
        <Feature Value="24"/>
        <Feature Value="3"/>
        <Feature Value="36"/>
        <Feature Value="17"/>
        <Feature Value="19"/>
        <Feature Value="62"/>
        <Feature Value="60"/>
    </Features>

**Comment by liangddyy** [comment]
感谢，修改后，变成了Personal版本。
