### ISSUE TITLE
MacOS Bundle的问题

### ISSUE THREAD

**Issue by parkycai** [tylearymf/UniHacker#20]
第二次运行就会起不来，仔细看了下，是因为.net单文件发布的binary，运行前会自解压到 $HOME/.net/ 下面，然后因为是sudo运行的，这个解压出来的目录owner是root，权限是 drwx------，不知为何第二次运行就没权限自解压到这个目录了。报错信息：
```
Failure processing application bundle.
Failed to commit extracted files to directory [/Users/***/.net/script/lLRXM_GMWE
```
目前能想到的work around是MacOS版本不要发布为SingleFile，反正最后是一个.app

**Comment by tylearymf** [comment]
可以去掉Mac的SingleFile模式，你那边有空的话可以测试下

**Comment by parkycai** [comment]
> 可以去掉Mac的SingleFile模式，你那边有空的话可以测试下

测试通过，可以这么改
