### ISSUE TITLE
Unity 2020_3_35f1 无法破解

### ISSUE THREAD

**Issue by 178435865** [tylearymf/UniHacker#23]

**Comment by tylearymf** [comment]
> _No description provided._

提供下Unity二进制文件

**Comment by tylearymf** [comment]
> > > _No description provided._
> > 
> > 
> > 提供下Unity二进制文件
> 
> 上传不了文件

压缩为zip包可以上传，或者转云盘之类的都可

**Comment by 178435865** [comment]
链接: https://pan.baidu.com/s/128VTsoi4oPFjLee_VkG53g 提取码: 7rur 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by tylearymf** [comment]
> 链接: https://pan.baidu.com/s/128VTsoi4oPFjLee_VkG53g 提取码: 7rur 复制这段内容后打开百度网盘手机App，操作更方便哦

你这个是国内特供版的，破解不了，去外网下载吧

**Comment by 178435865** [comment]
我的unity安装包是国外下载的哦

**Comment by 178435865** [comment]
https://unity3d.com/get-unity/download/archive

**Comment by 178435865** [comment]
https://unity3d.com/get-unity/download/archive

**Comment by 178435865** [comment]
https://download.unity3d.com/download_unity/18e4db7a9996/Windows64EditorInstaller/UnitySetup64-2020.3.35f1.exe?_gl=1*fctrlm*_gcl_aw*R0NMLjE2NDc5MzU3ODQuRUFJYUlRb2JDaE1JamRtd2s1X1o5Z0lWRnF5V0NoMUdoZ3BlRUFBWUFTQUFFZ0tZRWZEX0J3RQ..*_gcl_dc*R0NMLjE2NDc5MzU3ODQuRUFJYUlRb2JDaE1JamRtd2s1X1o5Z0lWRnF5V0NoMUdoZ3BlRUFBWUFTQUFFZ0tZRWZEX0J3RQ..

**Comment by tylearymf** [comment]
> https://download.unity3d.com/download_unity/18e4db7a9996/Windows64EditorInstaller/UnitySetup64-2020.3.35f1.exe?_gl=1*fctrlm*_gcl_aw*R0NMLjE2NDc5MzU3ODQuRUFJYUlRb2JDaE1JamRtd2s1X1o5Z0lWRnF5V0NoMUdoZ3BlRUFBWUFTQUFFZ0tZRWZEX0J3RQ..*_gcl_dc*R0NMLjE2NDc5MzU3ODQuRUFJYUlRb2JDaE1JamRtd2s1X1o5Z0lWRnF5V0NoMUdoZ3BlRUFBWUFTQUFFZ0tZRWZEX0J3RQ..

下载的时候如果检测到是国内地址，会自动转成国内地址下载的，比如上面的会变成 https://download.unitychina.cn/download_unity

**Comment by 178435865** [comment]
> 

我重新下载试试看
