### ISSUE TITLE
unity hub3.0无法登陆自己账号

### ISSUE THREAD

**Issue by F1Mac** [tylearymf/UniHacker#24]
Unity Hub3.0破解以后无法登陆自己的账号，点击登陆没有任何反应

**Comment by tylearymf** [comment]
> Unity Hub3.0破解以后无法登陆自己的账号，点击登陆没有任何反应

破解了是不能登录的。。。

**Comment by tylearymf** [comment]
> Unity Hub3.0破解以后无法登陆自己的账号，点击登陆没有任何反应

为啥还要登录自己账号，本来破解的意图就是不用登录账号就能用的

**Comment by kane9527-e** [comment]
他是想登录账号下载一些插件之类的吧

**Comment by tylearymf** [comment]
@F1Mac @kane9527-e  新版破解器支持登录账号了，可以试下
