### ISSUE TITLE
Unity 2020.3.30f1c1破解问题

### ISSUE THREAD

**Issue by Bull-Rush** [tylearymf/UniHacker#25]
Unity 2020.3.30f1c1不支持破解,请大佬提供个此版本或高版本的安装包,或者可行的破解方法,谢谢你.

**Comment by tylearymf** [comment]
> Unity 2020.3.30f1c1不支持破解,请大佬提供个此版本或高版本的安装包,或者可行的破解方法,谢谢你.

挂代理去这里下载 https://unity3d.com/get-unity/download/archive

**Comment by tylearymf** [comment]
> Unity 2020.3.30f1c1不支持破解,请大佬提供个此版本或高版本的安装包,或者可行的破解方法,谢谢你.

记得下载的时候走强制代理
