### ISSUE TITLE
2020.3.13f1被识别为国内特供版

### ISSUE THREAD

**Issue by CCTV-1** [tylearymf/UniHacker#26]
![1](https://user-images.githubusercontent.com/7350506/175050072-e74d5620-3132-44e1-bf22-4f1a20653a0a.png)

**Comment by tylearymf** [comment]
f1的也可能是国内版，你挂代理去下载国外版吧

**Comment by tylearymf** [comment]
> 我用这个版本可以将同版本号的外服游戏转为debug build，之前用c1的不行，所以我以为这个版本就是国外版。
> 
> 对Unity的破解是只有支持黑色主题一项吗？是的话能破解Hub就够了。

黑色主题不破解也有的，可能破解主要是为了Splash吧

**Comment by CCTV-1** [comment]
哦，那不破解也没事，我装Unity单纯为了做mod，不是用来做游戏。
