### ISSUE TITLE
UnityHub 3.1.2.0 破解成功后无法打开或创建项目

### ISSUE THREAD

**Issue by a412983219** [tylearymf/UniHacker#27]
如题，说许可证无效，但在许可证管理里，已经可以看到9999年到期，破解已成功

**Comment by tylearymf** [comment]
> 如题，说许可证无效，但在许可证管理里，已经可以看到9999年到期，破解已成功

还需要破解unity才能打开，破解hub只能打开hub

**Comment by a412983219** [comment]
> > 如题，说许可证无效，但在许可证管理里，已经可以看到9999年到期，破解已成功
> 
> 还需要破解unity才能打开，破解hub只能打开hub

破解过了，换了旧版本的unity hub 就可以

**Comment by tylearymf** [comment]
> > > 如题，说许可证无效，但在许可证管理里，已经可以看到9999年到期，破解已成功
> > 
> > 
> > 还需要破解unity才能打开，破解hub只能打开hub
> 
> 破解过了，换了旧版本的unity hub 就可以

那就不清楚了

**Comment by code-hasaki** [comment]
确实有这个问题，我的操作顺序是这样的，第一步安装UnityHub 3.1.2.0，使用工具提示UnityHub破解成功。第二步安装unity2019.4.40，使用工具提示Unity2019破解成功。第三步安装unity2020.3.36，使用工具提示Unity2020破解成功。实际的情况是，UnityHub和Unity2019确实破解成功了，启动运行都正常。但是Unity2020启动失败，提示(no valid unity editor license found. please activate your license.)，可能是Unity2020.3.36不识别新生成的Unity_lic.ulf，也可能是Unity2020.3.36没有破解成功。但是UnityHub和Unity2019破解成功，并且可以识别新生成的Unity_lic。

**Comment by code-hasaki** [comment]
刚刚用我之前发过你的通用补丁验证了一下，可以启动运行Unity2020.3.36，Unity_lic.ulf没有问题。所以说应该是UniHacker破解Unity2020.3.36失败了(虽然破解提示成功)。 @a412983219 的问题应该和我的一样，他的unity其实没有破解成功。

**Comment by tylearymf** [comment]
> 刚刚用我之前发过你的通用补丁验证了一下，可以启动运行Unity2020.3.36，Unity_lic.ulf没有问题。所以说应该是UniHacker破解Unity2020.3.36失败了(虽然提示破解成功)。 感觉@a412983219 的描述也是Unity没有破解成功。

那应该是流程上破解失败了

**Comment by tylearymf** [comment]
> 刚刚用我之前发过你的通用补丁验证了一下，可以启动运行Unity2020.3.36，Unity_lic.ulf没有问题。所以说应该是UniHacker破解Unity2020.3.36失败了(虽然提示破解成功)。 感觉@a412983219 的描述也是Unity没有破解成功。

你之前给的通用补丁逻辑也是匹配特征码去修改（跟我现在类似，不过他那个是运行时修改，我这个是静态修改），而且他那个修改不是公开的，unity那边可能就不知道，所以还能用

**Comment by tylearymf** [comment]
> > > 刚刚用我之前发过你的通用补丁验证了一下，可以启动运行Unity2020.3.36，Unity_lic.ulf没有问题。所以说应该是UniHacker破解Unity2020.3.36失败了(虽然提示破解成功)。 感觉@a412983219 的描述也是Unity没有破解成功。
> > 
> > 
> > 我这边试了2020.3.36是可以打开的，你下载的是这个版本吗 ![image](https://user-images.githubusercontent.com/14980389/176681174-5533b790-c19e-41f6-84e0-571ce35aad79.png)
> 
> 是的 git.master.7469419 原始的Unity.exe大小是82145856 字节，SHA256是D13B75DCA496B90F7AB52F32DEAC6AD1CCA8BD05E5A85EDB4584EB7351661E61 破解后的exe大小也是82145856 字节 ，SHA256是 52A786810256ADAE1AB387F127102C34A63C3974C009D63A6526962FFC8EA97E

一模一样的SHA256，我这边是直接就打开工程了的🤣

**Comment by code-hasaki** [comment]
![image](https://user-images.githubusercontent.com/71576322/176838022-348d1b78-afc5-4d2d-ad15-9a50ba32a483.png)
![image](https://user-images.githubusercontent.com/71576322/176838071-6e6ff2ca-df15-470f-a75c-297ad35d9d57.png)
无法打开或创建项目，弹出图一License error窗口，点击Open Hub按钮弹出图二窗口，你那边的Unity_lic.ulf能不能发来看看。

**Comment by tylearymf** [comment]
> ![image](https://user-images.githubusercontent.com/71576322/176838022-348d1b78-afc5-4d2d-ad15-9a50ba32a483.png) ![image](https://user-images.githubusercontent.com/71576322/176838071-6e6ff2ca-df15-470f-a75c-297ad35d9d57.png) @tylearymf 无法打开或创建项目，弹出图一License error窗口，点击Open Hub按钮弹出图二窗口，你那边的Unity_lic.ulf能不能发来看看。
[Unity_lic.zip](https://github.com/tylearymf/UniHacker/files/9026906/Unity_lic.zip)
你可以试试，还不行的话可以卸载Hub看下是不是Hub搞的鬼

**Comment by code-hasaki** [comment]
@tylearymf 不是Unity_lic.ulf的问题，Hub卸载了就可以启动Editor。Hub3.1.2和Unity2020.3.6之间的问题导致Editor不能启动。Hub3.1.2和Unity2019没问题。另外通用补丁可以启动Hub3.1.2和Unity2020.3.6，貌似是静态破解遗漏某些东西。我这边的Hub3.1.2的SHA256是4599168C0EA297996CC7C38514243FBEE681210700E80B0681E65B497E4B00F2。你那边的Hub安装包方便发一下么。

**Comment by code-hasaki** [comment]
![image](https://user-images.githubusercontent.com/71576322/176861125-1761075d-eb8e-4a3d-a319-3b1f2fefa88e.png)

@tylearymf 你发的连接是官方的最新地址，会下载3.2.0.0，一样有问题。我的3.1.2.0是国际版5月25号创建的版本。

**Comment by code-hasaki** [comment]
@tylearymf 另外你的Hub3.1.2大小133MB是从哪下载的？国际版的Hub3是102MB，中国版的Hub3是104MB，没有133MB的。

**Comment by tylearymf** [comment]
> @tylearymf 另外你的Hub3.1.2大小133MB是从哪下载的？国际版的Hub3是102MB，中国版的Hub3是104MB，没有133MB的。

我上面发的是安装后的Unity Hub.exe，不是Setup安装包，我就是上面发你的那个地址下的，但是那个时候是3.1.1版本，然后安装后自动升级为3.1.2的

**Comment by tylearymf** [comment]
更新
