### ISSUE TITLE
Unity 2019.4.20f1版本不支持破解

### ISSUE THREAD

**Issue by silentbird** [tylearymf/UniHacker#3]
![image](https://user-images.githubusercontent.com/14126362/167303333-102f3931-c3ee-4bc1-be40-c681022eee8c.png)

**Comment by tylearymf** [comment]
![image](https://user-images.githubusercontent.com/14980389/167305902-8f34811d-a9bc-468d-8c03-5acf72719a85.png)

**Comment by tylearymf** [comment]
https://download.unity3d.com/download_unity/6dd1c08eedfa/Windows64EditorInstaller/UnitySetup64-2019.4.20f1.exe

要下国际版的呀，不要下载国内版的
