### ISSUE TITLE
请问老哥M1版本的可以破了吗？

### ISSUE THREAD

**Issue by mikewu86** [tylearymf/UniHacker#32]
如题，我翻ISSUES，五月份的时候说ARM64无法破解。
我是M1，目前是这样的：
<img width="549" alt="WX20220628-223658@2x" src="https://user-images.githubusercontent.com/31203217/176211517-77fa446d-833c-4991-8a90-c61453932eba.png">

我想问问老哥有办法解决不~感谢感谢

**Comment by tylearymf** [comment]
> 如题，我翻ISSUES，五月份的时候说ARM64无法破解。 我是M1，目前是这样的： <img alt="WX20220628-223658@2x" width="549" src="https://user-images.githubusercontent.com/31203217/176211517-77fa446d-833c-4991-8a90-c61453932eba.png">
> 
> 我想问问老哥有办法解决不~感谢感谢

可以破，你翻下pr

**Comment by tylearymf** [comment]
> 我去翻了下，发现m1版本的3.2开始，3.3，3.4后面都有，唯独没有3.1，请问这个信息应该如何寻找呀？我去找一下加一下

给下邮箱我发你

**Comment by mikewu86** [comment]
860717151@qq.com，感谢
