### ISSUE TITLE
Hi. 国际版unity 2021.3.4f1 破解后无法创建项目，怎么解决？

### ISSUE THREAD

**Issue by RenFrog-Gamer** [tylearymf/UniHacker#34]
**你好大佬，我下载了国际版的unity 2021.3.4f1版本，装好之后用您的工具破解一直提示“ 国内特供版”，我目前机子上是有安装老的Unity 2018.4.36f1 (64-bit)，是不是这个老的unity版本影响了 该工具？**

我尝试过各种版本的UnityHub （hub 2.3.2，hub 2.4 ,以及现在的hub 3.1.2 c2）都是提示这个国内特供版，也多次重新下载了unity 2021.3.4f1 的安装包（这里是用拼接url的形式获得 **国际版2021.3.4f1的安装包**的，【URL：https://download.unity3d.com/download_unity/cb45f9cae8b7/Windows64EditorInstaller/UnitySetup64-2021.3.4f1.exe】）
也尝试过 用unityhub安装2021.3.4f1 ，都提示同样的文字。
是有什么系统缓存影响到工具的使用了吗？ 实在找到问题所在，故提问~

以上。
在这里非常感谢大佬的工具、

![) }X }G(~8WD9J(XAZY02O7](https://user-images.githubusercontent.com/82646834/176873527-483042b4-c05b-43c1-9672-a63830c959e8.png)

**Comment by tylearymf** [comment]
强制代理下载

**Comment by RenFrog-Gamer** [comment]
> 

就是 全程用vpn下载的试试？？ 那回头试试~
奇怪下载过来的 也只是f1的结尾，安装好后也是显示unity 2021.3.4f1，并没有-c1的后缀。
感谢我回头试试，不行再来问大佬~

**Comment by tylearymf** [comment]
> > 
> 
> 就是 全程用vpn下载的试试？？ 那回头试试~ 奇怪下载过来的 也只是f1的结尾，安装好后也是显示unity 2021.3.4f1，并没有-c1的后缀。 感谢我回头试试，不行再来问大佬~

是的，全程

**Comment by RenFrog-Gamer** [comment]
> > > 
> > 
> > 
> > 就是 全程用vpn下载的试试？？ 那回头试试~ 奇怪下载过来的 也只是f1的结尾，安装好后也是显示unity 2021.3.4f1，并没有-c1的后缀。 感谢我回头试试，不行再来问大佬~
> 
> 是的，全程

牛的！大佬~在这里先感谢了~

**Comment by RenFrog-Gamer** [comment]
**@tylearymf 你好，我用代理下载了2021.3.4f1后 也提示破解成功了，但是用unityhub新建项目提示“无法创建项目”，看日志是"授权验证失败"  ,请问大佬 可能是哪一步出问题了？？**
![)C)XSX}XC9C84M{UK66Y(T1](https://user-images.githubusercontent.com/82646834/177088755-744aac39-6cd8-4850-9019-c629c7f1c2ba.png)
![R4$RBS4NJWDXTV7}8E8%J3](https://user-images.githubusercontent.com/82646834/177088763-27235ff2-442b-4118-812a-9e652594eee6.png)
![S9RO(WLF3Y_08K)` (DU64D](https://user-images.githubusercontent.com/82646834/177088774-42cb96b7-3542-469b-9e1b-d6d4fbb01231.png)
![7K ~ASV3H$TPFVO 87SW6C](https://user-images.githubusercontent.com/82646834/177088780-57f2e07a-d89e-44b9-977a-39273ac9cd87.png)

@tylearymf

**Comment by tylearymf** [comment]
@RenFrog-Gamer 你的是什么版本的hub，在hub左上角

**Comment by RenFrog-Gamer** [comment]
> @RenFrog-Gamer 你的是什么版本的hub，在hub左上角
![5 18 3( N@Z$ZBE)O6H2Q%W](https://user-images.githubusercontent.com/82646834/177090079-df127572-4167-4753-b54d-0eca0cc689cf.png)

3.1.2-c2

**Comment by RenFrog-Gamer** [comment]
我现在的hub 版本已经许可证信息
![OW{VR@L`QI 5KZK%{FA4SA1](https://user-images.githubusercontent.com/82646834/177090573-ca922a4e-8363-4a49-b881-c4b787c1768c.png)

**Comment by tylearymf** [comment]
@RenFrog-Gamer 那你的 3.1.2 是所有unity版本都打不开，还是只是 2021.3.4打不开，或者你直接本地创建个空工程然后用 2021.3.4打开，这样试试？

**Comment by RenFrog-Gamer** [comment]
不是所有的都打不开，我依旧可以打开Unity 2018.4.36f1 (64-bit)的老项目；
本地新建了老的项目 用 2021.3.4也无法打开，提示同样的问题，

现在我在尝试老帖子里有提到的这个国际版hub:

挂代理下载
https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.exe
https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.dmg


> @RenFrog-Gamer 那你的 3.1.2 是所有unity版本都打不开，还是只是 2021.3.4打不开，或者你直接本地创建个空工程然后用 2021.3.4打开，这样试试？

**Comment by RenFrog-Gamer** [comment]
> @RenFrog-Gamer 那你的 3.1.2 是所有unity版本都打不开，还是只是 2021.3.4打不开，或者你直接本地创建个空工程然后用 2021.3.4打开，这样试试？
**把hub换成国际版的不带c的3.2.0 也没用，和3.1.2-c2 一样的提示，怎么感觉像是  2021.3.4f 没有真正的破解成功？？**
用hub修改项目的unity版本也只是提示了，点击确定没有成功，还是老版本。
![Uploading 2BNJ}@BABF_N_4H}%NBPI(U.png…]()
![$@3NKPQZ4QYT }@E6OGUA7I](https://user-images.githubusercontent.com/82646834/177093437-587a5047-c0dc-435d-bdc4-e320a1f13603.png)
![%D7)29CKSGQ000 A027(SP0](https://user-images.githubusercontent.com/82646834/177093449-fcc5b9b4-0ce8-4300-ac24-62960364fcf4.png)

**Comment by tylearymf** [comment]
@RenFrog-Gamer 你的unity版本是不是这样的信息：
![image](https://user-images.githubusercontent.com/14980389/177094273-755ea08f-7e83-4356-b801-ac884ac9ae91.png)

名称: Unity.exe
大小: 71756424 字节 (68 MiB)
SHA256: 24fce91bfc39b0882b36038b08b1202b0af93fc21823b5edf83ea83ce7b788f8

**Comment by RenFrog-Gamer** [comment]
不好意思，刚才重新卸载了2021.3.4版本 等了一会会，。
这是我的版本信息，好像是一致的， 和你的。

![S@L(CS} S)%Z37L0HW1(CAU](https://user-images.githubusercontent.com/82646834/177096775-47ec5a5e-9733-46ea-8309-4df8092bfc54.png)



> @RenFrog-Gamer 你的unity版本是不是这样的信息： ![image](https://user-images.githubusercontent.com/14980389/177094273-755ea08f-7e83-4356-b801-ac884ac9ae91.png)
> 
> 名称: Unity.exe 大小: 71756424 字节 (68 MiB) SHA256: 24fce91bfc39b0882b36038b08b1202b0af93fc21823b5edf83ea83ce7b788f8

不好意思，刚才重新卸载了2021.3.4版本 等了一会会，。
这是我的版本信息，好像是一致的， 和你的。

![S@L(CS} S)%Z37L0HW1(CAU](https://user-images.githubusercontent.com/82646834/177096775-47ec5a5e-9733-46ea-8309-4df8092bfc54.png)

**Comment by RenFrog-Gamer** [comment]
@tylearymf 
刚才又卸载重整重新用工具破解了一遍，依旧无法新建项目。

我就是想排除是不是先要破解hub再破解unity2021 才行，看来不是这样的。。。

如果大佬的这个版本，可以正常运行的话，劳烦告知下
![LZK~5_BQ6QT`2%JZU1@$B%1](https://user-images.githubusercontent.com/82646834/177097386-1a4ca19f-73f1-4542-9440-263cf9c7986b.png)

**Comment by tylearymf** [comment]
> @tylearymf 刚才又卸载重整重新用工具破解了一遍，依旧无法新建项目。
> 
> 我就是想排除是不是先要破解hub再破解unity2021 才行，看来不是这样的。。。
> 
> 如果大佬的这个版本，可以正常运行的话，劳烦告知下 ![LZK~5_BQ6QT`2%JZU1@$B%1](https://user-images.githubusercontent.com/82646834/177097386-1a4ca19f-73f1-4542-9440-263cf9c7986b.png)

你把Hub卸载掉试试能不能打开2021.3.4

**Comment by RenFrog-Gamer** [comment]
> 

好的  马上尝试~。
我再看下 我的SHA256

**Comment by RenFrog-Gamer** [comment]
> > @tylearymf 刚才又卸载重整重新用工具破解了一遍，依旧无法新建项目。
> > 我就是想排除是不是先要破解hub再破解unity2021 才行，看来不是这样的。。。
> > 如果大佬的这个版本，可以正常运行的话，劳烦告知下 ![LZK~5_BQ6QT`2%JZU1@$B%1](https://user-images.githubusercontent.com/82646834/177097386-1a4ca19f-73f1-4542-9440-263cf9c7986b.png)
> 
> 你把Hub卸载掉试试能不能打开2021.3.4

看起来好像可以打开，不过进度条还在loading。

以下是步骤截图：
![WL65_)O0_A C}90{X36QK3E](https://user-images.githubusercontent.com/82646834/177099369-f3783cc7-74fc-4da8-b0f8-0b69e7c4a2f1.png)

![LW755@)JMF @H0EBYG0S)F4](https://user-images.githubusercontent.com/82646834/177099280-669efd0b-5719-42fe-9988-d8c6a15e73d4.png)
![%__@%061`Q $K6SM9I _H~I](https://user-images.githubusercontent.com/82646834/177099268-99bfe04b-b6be-46a1-a338-a883fe7a9408.png)
![Y}GEPOMN 7{E91V7CB76XCK](https://user-images.githubusercontent.com/82646834/177099402-4f281891-0154-4310-af6b-709a0f21dee4.png)

**Comment by tylearymf** [comment]
@RenFrog-Gamer 那就是可以打开的，我有空再看看为啥在hub里打不开吧

**Comment by RenFrog-Gamer** [comment]
> @RenFrog-Gamer 那就是可以打开的，我有空再看看为啥在hub里打不开吧

**是这个2021.3.4f1 版本的问题？ 还是所有都这样？我换成2022.1还会出这个问题？

我可以换个可以用的版本试试~

我的SHA256码：**

PS E:\Program Files\Unity\Unity 2021.3.4f1\Editor> certutil -hashfile .\Unity.exe SHA256
SHA256 的 .\Unity.exe 哈希:
24fce91bfc39b0882b36038b08b1202b0af93fc21823b5edf83ea83ce7b788f8

**也是一样的。**

**Comment by tylearymf** [comment]
我这边的unity版本都是可以创建的，
![image](https://user-images.githubusercontent.com/14980389/177102253-d99a6de4-5fa4-4376-ac1c-fcfbfd9b3754.png)

**Comment by RenFrog-Gamer** [comment]
> 我这边的unity版本都是可以创建的， ![image](https://user-images.githubusercontent.com/14980389/177102253-d99a6de4-5fa4-4376-ac1c-fcfbfd9b3754.png)

**那我试试这个版本的。20221.1f1**
**感谢大佬的回复，如果还不行，可能是我电脑的环境经过多代unity破解被折腾了，**
