### ISSUE TITLE
大佬,你有测试macOS Unity2020.3.34 版本的吗

### ISSUE THREAD

**Issue by ZyleBallet** [tylearymf/UniHacker#35]

**Comment by tylearymf** [comment]
2020.3.34f1和2020.3.35f1都是测过的

**Comment by ZyleBallet** [comment]
是这样的我像请问一下,这里的这段

**Comment by ZyleBallet** [comment]
![截屏2022-07-05 16 06 49](https://user-images.githubusercontent.com/68416947/177280950-9dca897d-e6c0-4fc1-af97-007325724bfe.png)
是这样的,我在我的macos 2020.3.34f1 的unity X86_64unity可执行文件中,找不到这里的字节码.

**Comment by tylearymf** [comment]
> ![截屏2022-07-05 16 06 49](https://user-images.githubusercontent.com/68416947/177280950-9dca897d-e6c0-4fc1-af97-007325724bfe.png) 是这样的,我在我的macos 2020.3.34f1 的unity X86_64unity可执行文件中,找不到这里的字节码.

你是手动找吗，还是用我提供的工具显示不能破解

**Comment by ZyleBallet** [comment]
是我手动找的,ida和hex fiend 都找不到.你这工具,mac app打不开

**Comment by tylearymf** [comment]
> 是我手动找的,ida和hex fiend 都找不到.你这工具,mac app打不开

打不开有提示什么吗，之前的版本是可以打开的，你可以试试

**Comment by ZyleBallet** [comment]
Corrupt app bundle
Script missing from application bundle.

我试试看之前的版本



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月05日 16:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [tylearymf/UniHacker] 大佬,你有测试macOS Unity2020.3.34 版本的吗 (Issue #35) |

是我手动找的,ida和hex fiend 都找不到.你这工具,mac app打不开

打不开有提示什么吗，之前的版本是可以打开的，你可以试试

**Comment by tylearymf** [comment]
> 是我手动找的,ida和hex fiend 都找不到.你这工具,mac app打不开

你也可以自己在mac下构建下，前提是要有相关环境

**Comment by ZyleBallet** [comment]
嗯.2.6版本的app可以打开直接使用,不过这个项目的效果只是修改许可证的时间吧.其他好像就没了

**Comment by tylearymf** [comment]
> 嗯.2.6版本的app可以打开直接使用,不过这个项目的效果只是修改许可证的时间吧.其他好像就没了

Unity主程序才是主要，hub只是附带的

**Comment by ZyleBallet** [comment]
那就是没有成功了,用起来和个人版没有什么区别,一些功能也没有解锁,比如splash点击之类的.

**Comment by tylearymf** [comment]
> 那就是没有成功了,用起来和个人版没有什么区别,一些功能也没有解锁,比如splash点击之类的.

跟个人版差不多的，我是烦国内的3、4天就要登录验证激活许可证那套，才搞的这个

**Comment by tylearymf** [comment]
> > 
> 
> 好的,多谢了,其实我想破解掉一些限制功能,之前我自己也尝试修改了一些字节码,只是解锁了部分,有些实现始终没找到地方.

比如哪些限制功能？

**Comment by ZyleBallet** [comment]
![截屏2022-07-06 11 08 35](https://user-images.githubusercontent.com/68416947/177459814-9fc98334-9d06-4dd1-ab35-1203bd70623f.png)
比如这个

**Comment by tylearymf** [comment]
> ![截屏2022-07-06 11 08 35](https://user-images.githubusercontent.com/68416947/177459814-9fc98334-9d06-4dd1-ab35-1203bd70623f.png) 比如这个

![image](https://user-images.githubusercontent.com/14980389/177460955-51e39922-6f57-4318-a3ed-52d88fdb7709.png)

**Comment by tylearymf** [comment]
@ZyleBallet 还有其他的吗

**Comment by ZyleBallet** [comment]
嗯,你这个是你这个软件破解之后的吗.

**Comment by ZyleBallet** [comment]
我发的这个还不是原始版本的,这个是我自己手动修改之后,第一个把原来的不能点击弄成可以点击了.

**Comment by ZyleBallet** [comment]
这个是我unity版本

![截屏2022-07-06 11 26 26](https://user-images.githubusercontent.com/68416947/177461796-fb70fe13-ed58-4db9-bdd0-4c735db88df9.png)

我用了这个破解软件之后,原始的这两个按钮都是灰色的,那在我这边的unity估计是没有破解成功.

**Comment by tylearymf** [comment]
> 这个是我unity版本
> 
> ![截屏2022-07-06 11 26 26](https://user-images.githubusercontent.com/68416947/177461796-fb70fe13-ed58-4db9-bdd0-4c735db88df9.png)
> 
> 我用了这个破解软件之后,原始的这两个按钮都是灰色的,那在我这边的unity估计是没有破解成功.

是的，破解后的，你这个是国内版（c2），不能破解

**Comment by ZyleBallet** [comment]
好的,那我明白了,多谢大佬指明
