### ISSUE TITLE
2019.4.36f1 无法破解(mac)

### ISSUE THREAD

**Issue by jctn** [tylearymf/UniHacker#37]
mac
系统:11.4
UniHackerV2.7版本
Unity版本2019.4.36f1
选择Unity时闪退;闪退内容如下:
Process:               script [31556]
Path:                  /private/var/folders/*/UniHackerV2.7.app/Contents/Resources/script
Identifier:            script
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        UniHacker [31553]
Responsible:           UniHacker [31553]
User ID:               0

Date/Time:             2022-07-12 20:05:10.855 +0800
OS Version:            macOS 11.4 (20F71)
Report Version:        12
Anonymous UUID:        6C3A69AF-180C-2A96-7482-D8C8AEEF0533

Sleep/Wake UUID:       3ED54FE0-A220-4F8B-AC3D-AC84369FBD35

Time Awake Since Boot: 200000 seconds
Time Since Wake:       38000 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff2043292e __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff204615bd pthread_kill + 263
2   libsystem_c.dylib             	0x00007fff203b6411 abort + 120
3   libcoreclr.dylib              	0x0000000102be52db PROCAbort + 43
4   libcoreclr.dylib              	0x0000000102be520e PROCEndProcess(void*, unsigned int, int) + 238
5   libcoreclr.dylib              	0x0000000102e38da5 UnwindManagedExceptionPass1(PAL_SEHException&, _CONTEXT*) + 1029
6   libcoreclr.dylib              	0x0000000102e38e43 DispatchManagedException(PAL_SEHException&, bool) + 67

**Comment by tylearymf** [comment]
试一下之前的版本

**Comment by jctn** [comment]
> 试一下之前的版本

刚试了一下,Unity 2019.4.30f1也不行;

![Large GIF (320x280)](https://user-images.githubusercontent.com/6377240/178492332-2052eeb2-2cb9-40fd-92ba-b0994772bae9.gif)

看了一下UnityPatchInfos.cs ,是不是只能破解对应存在注释的版本?

**Comment by tylearymf** [comment]
> > 试一下之前的版本
> 
> 刚试了一下,Unity 2019.4.30f1也不行;
> 
> ![Large GIF (320x280)](https://user-images.githubusercontent.com/6377240/178492332-2052eeb2-2cb9-40fd-92ba-b0994772bae9.gif) [ ![Large GIF (320x280)](https://user-images.githubusercontent.com/6377240/178492332-2052eeb2-2cb9-40fd-92ba-b0994772bae9.gif) ](https://user-images.githubusercontent.com/6377240/178492332-2052eeb2-2cb9-40fd-92ba-b0994772bae9.gif) [ ](https://user-images.githubusercontent.com/6377240/178492332-2052eeb2-2cb9-40fd-92ba-b0994772bae9.gif)
> 
> 看了一下UnityPatchInfos.cs ,是不是只能破解对应存在注释的版本?

大部分是吧，因为我只搞了最新的2、3个小版本，旧的小版本没有去破解

**Comment by jctn** [comment]
> > > 试一下之前的版本
> > 
> > 
> > 刚试了一下,Unity 2019.4.30f1也不行;
> > 看了一下UnityPatchInfos.cs ,是不是只能破解对应存在注释的版本?
> 
> 大部分是吧，因为我只搞了最新的2、3个小版本，旧的小版本没有去破解

能请问一下UnityPatchInfos.cs中版本的hex串是怎么定位到的?如何确定需要追加的hex串?感谢~

**Comment by jctn** [comment]
我重新fork直接编译断点跑,可以破解2019.4.40f1了

**Comment by jctn** [comment]
感谢大佬工具

**Comment by MarkSenCN** [comment]
> 我重新fork编译断点跑，可以直接破解2019.4.40f1了

你有修改什么代码吗？我这边发现源码跑起来选择了unity.app就闪退了，提示的权限不够
