### ISSUE TITLE
大佬,可以让M1芯片的2021.3.6f1也支持吗

### ISSUE THREAD

**Issue by bobwong89757** [tylearymf/UniHacker#38]
Unity Hub国际版3.2 破解完不会自动有个虚拟账号
Unity M1版本2021.3.6f1 提示不支持破解

**Comment by tylearymf** [comment]
> Unity Hub国际版3.2 破解完不会自动有个虚拟账号 Unity M1版本2021.3.6f1 提示不支持破解

1、 Hub破解完有无虚拟账号，是不影响使用的
2、那个破解的我周末看下

**Comment by bobwong89757** [comment]
感谢大佬

**Comment by tylearymf** [comment]
更新
