### ISSUE TITLE
Unity 2021.3.2f1 破解后提示没有许可证，但HUB已经破解

### ISSUE THREAD

**Issue by kane9527-e** [tylearymf/UniHacker#4]
![image](https://user-images.githubusercontent.com/9569527/167576999-8f6ddf1d-8473-4af3-b7d9-d4ccba22768b.png)

**Comment by tylearymf** [comment]
你检查下这个文件是否创建成功了 C:\ProgramData\Unity\Unity\Unity_lic.ulf

**Comment by foreversos** [comment]
同样的问题...
目录下面有文件

**Comment by kane9527-e** [comment]
同楼上 许可证是创建了的，目录下有文件，在新电脑上也如此 国外国内hub都如此

**Comment by kane9527-e** [comment]
建议大佬不要开源全部，核心代码请加密混淆，否则你一出官方就会修补

**Comment by TriggerB0x** [comment]
> > 我觉得有可能是这个版本更新时间是五月六号,但是UniHacker更新时间是五月五号的问题
> 
> 有点道理,谁网速快可以试试下载2021.3.1F试试

我试过五月四号更新的Unity 2020.3.34f1 (64-bit)是没有问题的

**Comment by kane9527-e** [comment]
那就是新版本的改了啥代码特意和大佬对着更新......

**Comment by tylearymf** [comment]
> 那就是新版本的改了啥代码特意和大佬对着更新......

那可能是unity改了啥吧。。你先用2021.3.1f1吧，3.2f1的我晚点看看

**Comment by kane9527-e** [comment]
我下了2021.3.1f1直接打开原有项目无反应，新建还是如此，我才是HUB更新的郭

**Comment by tylearymf** [comment]
> 我下了2021.3.1f1直接打开原有项目无反应，新建还是如此，我才是HUB更新的郭

2021.3.1f1 这个版本是可以破解的，那你把hub卸载掉，看看能不能打开项目

**Comment by tylearymf** [comment]
> 我下了2021.3.1f1直接打开原有项目无反应，新建还是如此，我才是HUB更新的郭

你不卸载hub的话可以试试，把网络断了，看看

**Comment by kane9527-e** [comment]
> > 我下了2021.3.1f1直接打开原有项目无反应，新建还是如此，我才是HUB更新的郭
> 
> 2021.3.1f1 这个版本是可以破解的，那你把hub卸载掉，看看能不能打开项目
断了下网可以了,Unity 2021.3.2f1目前还是不行的.

**Comment by kane9527-e** [comment]
> Reference

![image](https://user-images.githubusercontent.com/9569527/167632779-caf009a1-46fa-4e6d-879c-979750fd2a5c.png)
我这19 21都可以 最新20新建项目没问题,老项目打开就提示

**Comment by tylearymf** [comment]
> > Reference
> 
> ![image](https://user-images.githubusercontent.com/9569527/167632779-caf009a1-46fa-4e6d-879c-979750fd2a5c.png) 我这19 21都可以 最新20新建项目没问题,老项目打开就提示

刚上传了1.3版本，支持破解2021.3.2f1了😉

**Comment by tylearymf** [comment]
> 我觉得有可能是这个版本更新时间是五月六号,但是UniHacker更新时间是五月五号的问题

还真是哈哈哈😁

**Comment by tylearymf** [comment]
> 我下了2021.3.1f1直接打开原有项目无反应，新建还是如此，我才是HUB更新的郭

你2021.3.1f1破解了都打不开项目？？这不可能啊

**Comment by whl160118** [comment]
> 

大佬 有2021.3.x的国际版离线安装包下载地址吗。
