### ISSUE TITLE
UniHacker v2.8 破解2018.4.36f1 无法启动 (MacOS)

### ISSUE THREAD

**Issue by BambooStudioGame** [tylearymf/UniHacker#42]
Unity Hub 3.2.0 已经破解,
由于工作需要我电脑上同时存在多个版本的unity  他们分别是  2017.4.40f1 , 2018.4.36f1 , 2019.4.40f1 , 2020.3.35f1 , 2021.3.7f1 保证他们都是国际版.
我分别使用UniHacker 先对hub 破解, 然后分别在对unity 破解,他们都显示破解成功, 然后分别在Hub中运行不同版本的unity发现 2019,2020,2021 可以正常运行,并且破解有效, 但是运行2017,2018 则出现在MacOS控制台显示一下uniyt图标后自动就关闭了, 无法正常启动Unity,期初以为下载的非国际版,所以又以vpn全局模式重新下载安装,发现也是同样的现象, 还希望大佬看能否解决2017,2018破解启动问题.

**Comment by tylearymf** [comment]
@BambooStudioGame 你试下卸载hub后，看能不能打开2018和2017

**Comment by BambooStudioGame** [comment]
之前我没卸载hub的时候单独运行过2018,它会出现 license Error 的界面,刚刚我删除了Hub单独运行也是出现的相同的界面
![Uploading WX20220803-152826@2x.png…]()

**Comment by BambooStudioGame** [comment]
<img width="999" alt="WX20220803-152826@2x" src="https://user-images.githubusercontent.com/109714433/182550248-d984ec91-3829-4f10-aa35-f2f1239dfd96.png">
刚刚的截图

**Comment by tylearymf** [comment]
那可能是补丁码有问题了，后面有空我再看看

**Comment by BambooStudioGame** [comment]
好的,麻烦大佬了

**Comment by tylearymf** [comment]
或者再试下把网断了看看能不能打开

**Comment by BambooStudioGame** [comment]
刚刚试了,单独运行还是和上面的截图同样的界面

**Comment by tylearymf** [comment]
用最新版试下，破解后第一次打开时记得先断下网再打开，后续就不用断网了，不然2018、2017版会提示要登录账号

**Comment by weizuojiazhi** [comment]
求这个软件怎么使用，mac，是点击UniHacker.app吗

**Comment by tylearymf** [comment]
> 求这个软件怎么使用，mac，是点击UniHacker.app吗

双击.app打开，选择你本地安装好的unity或unityhub，最后点击破解即可

**Comment by weizuojiazhi** [comment]
> > 求这个软件怎么使用，mac，是点击UniHacker.app吗
> 
> 双击.app打开，选择你本地安装好的unity或unityhub，最后点击破解即可

我双击之后先是自己加了可执行权限给UniHacker.app/Contents/MacOS/UniHacker，然后提示没有script，自己在UniHacker.app/Contents/Resources下面创建了script的空文件夹，再次运行没有可以选择unity的地方，今天下的最新版本

**Comment by codezjg** [comment]
hub 3.0 版本破解后没有关闭hub自动更新， 当hub更新后， hub的破解就失效了，需要重新再次破解，希望破解hub后 同时能把hub的自动更新也能关掉

**Comment by tylearymf** [comment]
> hub 3.0 版本破解后没有关闭hub自动更新， 当hub更新后， hub的破解就失效了，需要重新再次破解，希望破解hub后 同时能把hub的自动更新也能关掉

后续有空我加个选项吧，有些人是要自动更新的，你新开个issue吧
