### ISSUE TITLE
大佬劳烦支持下 v2021.3.8f1, 感激

### ISSUE THREAD

**Issue by maxtoto** [tylearymf/UniHacker#45]
Unity.exe  [下载连接](https://xagm7wit7b.feishu.cn/file/boxcnYoQSEHFwYW34ZabWVlyuse)

**Comment by tylearymf** [comment]
好，我周末看下

**Comment by tylearymf** [comment]
你这个本来就支持的呀，用最新版本的

![image](https://user-images.githubusercontent.com/14980389/185116944-123cfc00-836c-47a9-aaaf-76c0bdec993f.png)
