### ISSUE TITLE
2020.3.35f1用这个告诉我已破解，可是打开导出设置，logo还是取消不了

### ISSUE THREAD

**Issue by XingShuiYueHe** [tylearymf/UniHacker#46]

**Comment by tylearymf** [comment]
你切到android平台试试能不能取消，还有截个图看看

**Comment by XingShuiYueHe** [comment]
https://github.com/XingShuiYueHe/PngShare/blob/main/QQ%E5%9B%BE%E7%89%8720220818093150.png，然后这边https://github.com/XingShuiYueHe/PngShare/blob/main/QQ%E5%9B%BE%E7%89%8720220818093141.png，这个没法移除，但是可以隐藏，跟我想的不一样（我想的是可以移除替换），这个算正常么还是我操作问题

**Comment by XingShuiYueHe** [comment]
1. https://github.com/XingShuiYueHe/PngShare/blob/main/QQ%E5%9B%BE%E7%89%8720220818093150.png
2. https://github.com/XingShuiYueHe/PngShare/blob/main/QQ%E5%9B%BE%E7%89%8720220818093141.png
3. 这边logo是可以隐藏但不能移除，这是正常的还是我操作不对？

**Comment by tylearymf** [comment]
* 禁用掉 Show Unity Logo
![image](https://user-images.githubusercontent.com/14980389/185277124-ee191342-fbc6-49ed-b0b5-80447de04b4f.png)

**Comment by XingShuiYueHe** [comment]
好的，感谢回答

**Comment by XingShuiYueHe** [comment]
明白了，感谢答复
