### ISSUE TITLE
2020.2.7f1(x64) Not Support Patch

### ISSUE THREAD

**Issue by huahuacn** [tylearymf/UniHacker#47]
<img width="520" alt="image" src="https://user-images.githubusercontent.com/31203217/185671337-b5ef7921-e84d-4a98-bede-aab7b4966f81.png">
老哥能支持一下吗

这是Unity文件~~
链接: https://pan.baidu.com/s/1LLwMYPN_igEhkzPSQTzNGA?pwd=sp2p 提取码: sp2p 
--百度网盘

**Comment by tylearymf** [comment]
用最新的试试
