### ISSUE TITLE
十分感谢作者。有个UPM的问题想请教一下..我没法用UnityPackage下载.

### ISSUE THREAD

**Issue by jjjjax** [tylearymf/UniHacker#48]
我无论如何都连不上
packages.unity.com
download.packages.unity.com
不知道为啥..哪怕开VPN也无法连接.

表现出来就是Unity Package的Registry永远连不上，无法下载安装.

有什么办法我能绕过它们去用国内的地址吗？
谢谢了

**Comment by tylearymf** [comment]
表现是啥样的，我这边是可以正常使用的

**Comment by tylearymf** [comment]
![image](https://user-images.githubusercontent.com/14980389/185915454-3e912303-e42a-4d1b-ae19-74c18213c861.png)

**Comment by tylearymf** [comment]
我看你这个图挺正常的啊

选版本点这个
![image](https://user-images.githubusercontent.com/14980389/185919353-3aff68d0-6bdf-428b-b4c4-1e09886ff368.png)

本地包选这个模式
![image](https://user-images.githubusercontent.com/14980389/185919573-d66570b9-3904-4d99-ab47-c0f7933d189a.png)

你可以去看下UPM的介绍

**Comment by jjjjax** [comment]
抱歉截图太急了，急着回家…
点开版本选择以后只有一个版本，任何版本的unity默认项目都只能用我现在这些。

不是in project，就是registry

**Comment by jjjjax** [comment]
unity应该只有国外版和特供版吧？
我回家自己下一个国外版看看。看看是不是公司网络的问题…

**Comment by jjjjax** [comment]
这两天比较忙，在家也没试过。。。
但是公司尝试了一下个人版，居然都能够正常下载..
我现在个人版是这样的：
老版本的UnityHub(2.4.5)，在Unity官网通过hub按钮下载海外版，不crack，就用个人版激活，然后所有包都是正常的...不知道为啥..
现在想法是个人版把可能需要的包都缓存下来，之后crack就OK了。
