### ISSUE TITLE
Unity Hub v3.2.0 patched but fail to open Unity Editor v2020.3.38f1

### ISSUE THREAD

**Issue by tracer8** [tylearymf/UniHacker#49]
Hi,
Unity Hub v3.2.0 patched success, but when i try to open project  Editor v2020.3.38f1 . It is fail to open like screenshot below.

![PicPick_2022-08-28_003](https://user-images.githubusercontent.com/15725821/187061203-3b0bec80-e6b5-480f-ad37-968a3e193ed9.jpg)

**Comment by tylearymf** [comment]
Did you just crack UnityHub.exe? You also need to crack Unity.exe to open the project

**Comment by tracer8** [comment]
Yes, I'm crack 2 of them.
Does i need to Run As Admin mode on patcher?

**Comment by tylearymf** [comment]
> Yes, I'm crack 2 of them.
> 
> * Checked Unity Hub have license to year 9999
> * Checked Unity Editor folder have diff .exe file
> 
> Does i need to Run As Admin mode on patcher?

Yes, run as admin

**Comment by tracer8** [comment]
I tried but still same error.

![PicPick_2022-08-28_005](https://user-images.githubusercontent.com/15725821/187066150-26afd4d5-adea-4499-a1b1-2f5c61b88500.jpg)
![PicPick_2022-08-28_004](https://user-images.githubusercontent.com/15725821/187066151-3e27437d-d0dc-49c1-a859-c225389a63b7.jpg)

**Comment by tylearymf** [comment]
Send me unity.exe and I'll check the patch

**Comment by tracer8** [comment]
Here you go:
https://www52.zippyshare.com/v/QpySbbwh/file.html

**Comment by tracer8** [comment]
Patched exe:
https://www52.zippyshare.com/v/K9PSkMmt/file.html

**Comment by tylearymf** [comment]
Your unity.exe has been successfully cracked. It seems that there is a problem with the unity hub. You can try to uninstall the hub, and then double-click unity.exe to open the project. You can go here to download a new version of the hub, and then try to crack it.  https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.exe

**Comment by tracer8** [comment]
> Your unity.exe has been successfully cracked. It seems that there is a problem with the unity hub. You can try to uninstall the hub, and then double-click unity.exe to open the project. You can go here to download a new version of the hub, and then try to crack it. https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.exe

I did, uninstall hub, crack hub then crack editor, open Editor -> It open Hub then error show up:
"No valid license key found"
I'm install newest Hub 3.2.0 and editor v2020.3.38f1.

**Comment by tylearymf** [comment]
Try uninstalling the hub, double-click unity.exe to open the project

**Comment by tracer8** [comment]
I did, but not fix this issue.

**Comment by tylearymf** [comment]
Can open the project?

**Comment by tracer8** [comment]
Yes, it always open popup "No valid license key found"

**Comment by tylearymf** [comment]
> Yes, it always open popup "No valid license key found"

ok, I check the problem of unityhub

**Comment by tracer8** [comment]
> > Yes, it always open popup "No valid license key found"
> 
> ok, I check the problem of unityhub

Yes, you can download Unity 2020.3.38f1 then try to crack it.

**Comment by tylearymf** [comment]
Try the new release version.

**Comment by tracer8** [comment]
@tylearymf It is working now!
Thank you! 👍
