### ISSUE TITLE
2020.3.33&2020.3.34破解后无法打开工程

### ISSUE THREAD

**Issue by luoxiali** [tylearymf/UniHacker#5]
使用UniHacker破解成功后，在Hub3.0.1中使用Unity2020.3.33新建工程，打开后报错：
1、GetLoadedImportedAssetsAndArtifactIDs called with invalid artifactID
2、Assertion failed on expression: 'it->second.IsValid()'
![error](https://user-images.githubusercontent.com/26451909/167976381-7707567e-6ca7-4900-94f7-b833289ec33e.png)
关闭后再此打开前面创建的工程，则无法再次从Hub中打开

**Comment by tylearymf** [comment]
试试新建个空工程？

**Comment by tylearymf** [comment]
实在打不开，你把 %HOMEPATH%/AppData/Local/Unity/Editor 目录下 Editor.log 删掉，然后打开工程，等它一会儿在把 Editor.log 里面的内容复制上来看看

**Comment by tylearymf** [comment]
![image](https://user-images.githubusercontent.com/14980389/168018080-a51e68db-329a-4f99-a4e3-23e62e1899e0.png)
2020.3.33f1可以打开，关掉再开也是可以的，但是2020.3.34f1确实打不开。。。晚点我看看吧

**Comment by tylearymf** [comment]
更新

**Comment by luoxiali** [comment]
好的，谢谢！！
