### ISSUE TITLE
Use my own Unity Account after patch?

### ISSUE THREAD

**Issue by tracer8** [tylearymf/UniHacker#50]
Hi,
After crack, my own account on Unity Hub is logout and current account is Anonymous.
I need to use Unity Account with RemoteConfig and Analytics
So can i login and use my own account?
Cause when  i try to logout, then press login button, nothing happen.

![PicPick_2022-08-29_001](https://user-images.githubusercontent.com/15725821/187119921-1d3d092c-85ef-4b1d-adb2-6d4584bae03e.jpg)

**Comment by tylearymf** [comment]
No, you can't, if you try to log in, unity will ban it, that's the downside of cracking

**Comment by tracer8** [comment]
@tylearymf Can you research this old crack of 3.0.1 i have?
Because on this crack method, i still can crack and login success too. After Unity Hub 3.2.0 , the author of this crack is offline, and not update it, so i found you.
His method is simple modify app.asar  to make same result as your method.

UnityHub-3.0.1-Windows-Patch.zip
https://www99.zippyshare.com/v/aXBlxhww/file.html

UnityHub-3.0.1-app.asar-macOS-Patch.zip
https://www99.zippyshare.com/v/KQmm1PNN/file.html

**Comment by tylearymf** [comment]
ok, i'll do some research on the weekend

**Comment by tylearymf** [comment]
Try the new release version

**Comment by parkycai** [comment]
@tylearymf 这个账号登陆安全吗？会有被ban的可能吗

**Comment by tylearymf** [comment]
> @tylearymf 这个账号登陆安全吗？会有被ban的可能吗

有几率被ban，不过应该比其他的破解的ban的几率小，因为我干掉了Licensing的检测，不过就算被ban了，再注册个账号就行了，毕竟gmail有无限账号😏😏

**Comment by tracer8** [comment]
> @tracer8 Try the new release version

It is working very good. 

> @tylearymf 这个账号登陆安全吗？会有被ban的可能吗

I'm use old one for long time, no issue, but anyway, use at your own risk.
