### ISSUE TITLE
Not supported linux versions binaries: Hub-v3.2.0, 2019.4.40f1 & 2021.3.7f1

### ISSUE THREAD

**Issue by shetabcnet** [tylearymf/UniHacker#52]
Hi!
Here are the binaries:
[https://mega.nz/file/i5sAzIYB#jXvXYK_UJGmhDyrrCR7wQJy56tRSkhjQgXhIcU17QCY](https://mega.nz/file/i5sAzIYB#jXvXYK_UJGmhDyrrCR7wQJy56tRSkhjQgXhIcU17QCY)

Thank you!

**Comment by tylearymf** [comment]
@shetabcnet @almanesa Try the new version.

**Comment by shetabcnet** [comment]
Great!
Thank you.
