### ISSUE TITLE
MacOS下首次破解成功之后, 重新安装Unity之后显示已破解, 但是实际上应该没有破解, 且无法打开Unity

### ISSUE THREAD

**Issue by 452283662** [tylearymf/UniHacker#53]
MacOS下首次破解成功之后, 重新安装Unity之后UniHacker显示已破解, 破解按钮无法点击, 但是实际上应该没有破解, 且无法打开Unity, 提示说证书无效.

**Comment by tylearymf** [comment]
卸载掉Unity，重新安装后，再破解试试
