### ISSUE TITLE
hack 2021.3.9f1之后 upm用不了

### ISSUE THREAD

**Issue by CodeMasterYi** [tylearymf/UniHacker#55]
如题，报错如下：
```Log
Failed to resolve packages: Upm configuration is invalid:
  "npmAuth.http://localhost:4873" contains a conflict between exclusive peers [token, _auth]. No packages loaded.

A re-import of the project may be required to fix the issue or a manual modification of /Volumes/JokeMaker/Workspace/Hello2021/Packages/manifest.json file.
```

**Comment by tylearymf** [comment]
你搞了个本地npm服务器？

**Comment by tylearymf** [comment]
你试试通过hub创建个新工程试试，如果还有问题把工程压缩发我

**Comment by CodeMasterYi** [comment]
> 你搞了个本地npm服务器？

没弄本地npm服务器

**Comment by CodeMasterYi** [comment]
[Hello2021.zip](https://github.com/tylearymf/UniHacker/files/9486485/Hello2021.zip)

**Comment by tylearymf** [comment]
![image](https://user-images.githubusercontent.com/14980389/188355758-85d6a4ff-3a23-4bc1-9145-716816065f75.png)
![image](https://user-images.githubusercontent.com/14980389/188355831-c59f1991-c3c8-4f69-99a9-a51421055224.png)

@CodeMasterYi 挺正常的呀

**Comment by CodeMasterYi** [comment]
我电脑上有之前别的方式hack的Unity2018版本，会不会跟这个有关系？

**Comment by CodeMasterYi** [comment]
如果要把那个Unity2018改成用你这种方式hack的话，是不是要把什么文件删了？

**Comment by tylearymf** [comment]
> 我电脑上有之前别的方式hack的Unity2018版本，会不会跟这个有关系？

应该没有关系

**Comment by tylearymf** [comment]
你试下将 Unity.exe、Unity Hub.exe 加入代理，再重新打开Hello2021工程，看看有没有问题

**Comment by CodeMasterYi** [comment]
我现在用的Mac版本，我回头也可以试试Windows版本

**Comment by tylearymf** [comment]
Mac版装个Proxifier，把那两个软件加入代理

**Comment by CodeMasterYi** [comment]
你用mac吗？我有个upm配置(~/.upmconfig.toml)里不知道什么时候塞了点东西
```
[npmAuth."http://localhost:4873/"]
...
```
我怀疑是别的破解方式自动给我修改的～

**Comment by CodeMasterYi** [comment]
删了这个配置之后，可以了！谢谢陪我一起忙和～[/爱心]

**Comment by tylearymf** [comment]
> 你用mac吗？我有个upm配置(~/.upmconfig.toml)里不知道什么时候塞了点东西
> 
> ```
> [npmAuth."http://localhost:4873/"]
> ...
> ```
> 
> 我怀疑是别的破解方式自动给我修改的～

我本地没有这个文件呢
