### ISSUE TITLE
Mac下Hub v3.3.0 用最新3.6 patch后无法打开

### ISSUE THREAD

**Issue by bobwong89757** [tylearymf/UniHacker#56]
大佬可以支持一下吗? hub会自动升级到3.3.0, 重新patch还是打不开, 卸载重装hub也不行

**Comment by tylearymf** [comment]
> 大佬可以支持一下吗? hub会自动升级到3.3.0, 重新patch还是打不开, 卸载重装hub也不行

是双击hub后，没有任何反应吗，有没有报错的弹窗

**Comment by bobwong89757** [comment]
> 

没有任何弹窗

**Comment by tylearymf** [comment]
那你把 Unity Hub.app/Contents/resources/app.asar.bak、Unity Hub.app/Contents/resources/app.asar.unpacked 这两个压缩成一个文件发我，我调试看看

**Comment by codezjg** [comment]
是的3.3 无法打开hub，今天早上我又还原到3.2，才能启动

**Comment by tylearymf** [comment]
@bobwong89757 那你用3.5的patch看看能不能打开

**Comment by tylearymf** [comment]
> 是的3.3 无法打开hub，今天早上我又还原到3.2，才能启动

嗯，我只测试了win下的Hub 3.3是没问题的，mac的没测试

**Comment by bobwong89757** [comment]
> 那你把 Unity Hub.app/Contents/resources/app.asar.bak、Unity Hub.app/Contents/resources/app.asar.unpacked 这两个压缩成一个文件发我，我调试看看

链接: https://pan.baidu.com/s/1YglJn5E47OxG77FF6apCWA 提取码: ic0a 
--来自百度网盘超级会员v6的分享

**Comment by tylearymf** [comment]
> @bobwong89757 那你用3.5的patch看看能不能打开

@bobwong89757 用3.5的试试？

**Comment by bobwong89757** [comment]
> > @bobwong89757 那你用3.5的patch看看能不能打开
> 
> @bobwong89757 用3.5的试试？

试过了, 也不行

**Comment by bobwong89757** [comment]
hub还原成3.2了, 不过可以修改一下app里面的hubAutoUpdate.js文件
![image](https://user-images.githubusercontent.com/6356061/190338901-b03e8982-3509-48eb-8982-fb96aa987b81.png) 
![image](https://user-images.githubusercontent.com/6356061/190338980-10826a4e-2504-4ef2-9a46-3ecb888b5d85.png)

**Comment by bobwong89757** [comment]
这样就可以不更新hub啦, 我写了个shell可以直接在mac上编译了,不过crack这边的逻辑还需要和大佬多学习一下

**Comment by tylearymf** [comment]
试试新版
