### ISSUE TITLE
希望破解hub的时候给一个选项能同时关闭自动更新hub

### ISSUE THREAD

**Issue by codezjg** [tylearymf/UniHacker#57]
希望破解hub的时候给一个选项能同时关闭自动更新hub

**Comment by CodeMasterYi** [comment]
> 希望破解hub的时候给一个选项能同时关闭自动更新hub

https://blog.csdn.net/weixin_43749570/article/details/106564885
@codezjg 你要的是这个？

**Comment by codezjg** [comment]
这个是手动操作，而且目前不确定删除文件后是否还会出现更新。

**Comment by tylearymf** [comment]
试试新版

**Comment by codezjg** [comment]
谢谢。
