### ISSUE TITLE
无法破解Unity2022.3.33f1

### ISSUE THREAD

**Issue by ywh0512** [tylearymf/UniHacker#58]
下载的国际版Unity2020.3.33f1，破解时文件状态兰显示【国内特供版不支持破解】，我明明下载的是国际版

**Comment by tylearymf** [comment]
[README](https://github.com/tylearymf/UniHacker/blob/main/README.md)

**Comment by lcf8858** [comment]
我也是同意的问题 Unity2020.3.33f1 同上。

**Comment by tylearymf** [comment]
> 我也是同样的问题 Unity2020.3.33f1 同上。

看文档

**Comment by ywh0512** [comment]
看到文档了，文档说下载的话要全程代理，但是我就是全程代理下载的，还是会重定向为国内版，本来以为多试几次就可以，但运气很不好，每次都重定向为国内版

**Comment by tylearymf** [comment]
> 看到文档了，文档说下载的话要全程代理，但是我就是全程代理下载的，还是会重定向为国内版，本来以为多试几次就可以，但运气很不好，每次都重定向为国内版

那你这个代理不是全局的，这个跟代理设置有关，无关运气

**Comment by ywh0512** [comment]
全局？？   我第一次下载的就是国际版，后面就都成国内版了，好吧  我再试试

**Comment by tylearymf** [comment]
> 全局？？ 我第一次下载的就是国际版，后面就都成国内版了，好吧 我再试试

建议用Chrome+swichyomega或者idm+proxifier

**Comment by ywh0512** [comment]
OK  感谢
