### ISSUE TITLE
破解成功后 显示无效的license

### ISSUE THREAD

**Issue by milesmou** [tylearymf/UniHacker#60]
已破解unity 破解工具显示已破解了
2021.3.10f1

**Comment by tylearymf** [comment]
@milesmou 你是用Hub打开的工程吗？Hub要破解了才能打开的。

**Comment by milesmou** [comment]
@tylearymf hub已经是破解了的  以前破解的unity是正常使用的  打开新安装的2021就提示无效的license

**Comment by tylearymf** [comment]
> @tylearymf hub已经是破解了的 以前破解的unity是正常使用的 打开新安装的2021就提示无效的license

那你重新用软件 还原Hub、还原Unity，再执行 破解Hub、破解Unity试试，我这边2021.3.10f1是可以正常通过hub打开的

**Comment by milesmou** [comment]
> 那你重新用软件 还原Hub、还原Unity，再执行 破解Hub、破解Unity试试，我这边2021.3.10f1是可以正常通过hub打开的

哈哈 按你的步骤都还原一下就好了
