### ISSUE TITLE
Some ARM love?

### ISSUE THREAD

**Issue by noendltd** [tylearymf/UniHacker#62]
Thanks for stepping up with this project, so... can we get some love for ARM macs?

2022.1.18f1 (ARM64)
Unity Hub 3.0.1

**Comment by tylearymf** [comment]
@noendltd Give me some screenshots.

**Comment by noendltd** [comment]
Here you go, let me know if you need more

![Screen Shot 2022-09-30 at 12 44 20 PM](https://user-images.githubusercontent.com/3512371/193243409-d4739da3-a1d1-41ce-b986-7ece54ac0bff.png)

![Screen Shot 2022-09-30 at 12 44 42 PM](https://user-images.githubusercontent.com/3512371/193243305-a5f6cc39-091c-4e53-b2a0-47ef7b104ad4.png)




> @noendltd Give me some screenshots.

**Comment by tylearymf** [comment]
@noendltd I'll check the patch later

**Comment by tylearymf** [comment]
https://drive.google.com/file/d/1Rla8yl0P9-xDj0N8znBfx9m3pwZfoOj2/view?usp=sharing

@noendltd Try this beta version, because I don't have an M1 device, I'll submit it later if can be cracked

**Comment by noendltd** [comment]
@tylearymf 
I can confirm that you are the first one to manage to do this for an apple silicon unity version. Thanks allot

![Screen Shot 2022-10-01 at 12 21 29 PM](https://user-images.githubusercontent.com/3512371/193402703-81f517cb-c8aa-4966-bc29-7740d07570c7.png)

![Screen Shot 2022-10-01 at 12 24 06 PM](https://user-images.githubusercontent.com/3512371/193402708-20303451-bd29-42ba-b8ad-0a67840aaac3.png)
