### ISSUE TITLE
Can not use Sign In function 2022.1.18f1

### ISSUE THREAD

**Issue by raku10dev** [tylearymf/UniHacker#64]
Unity version: 2022.1.18f1
When I pressed Sign In button on Unity Editor. Nothing is happens. I can not login into my account.
Maybe is this bug by Patcher ?

Please check this bug please !!!

**Comment by tylearymf** [comment]
> Unity version: 2022.1.18f1 When I pressed Sign In button on Unity Editor. Nothing is happens. I can not login into my account. Maybe is this bug by Patcher ?
> 
> Please check this bug please !!!

You can only log in through Unity Hub, not Unity Editor

**Comment by tylearymf** [comment]
@raku10dev You need to select the login account option when cracking

**Comment by raku10dev** [comment]
@tylearymf Thank you so much ! I got it !
