### ISSUE TITLE
2021.2.18f1

### ISSUE THREAD

**Issue by dreamVisitor** [tylearymf/UniHacker#65]
I downloaded both unity2021.2.18f1 and unity2021.3.11f1.
Unity2021.3.11f1 is fine.
But, Unity2021.2.18f1 reminds me that it is a domestic special offer version.

**Comment by tylearymf** [comment]
国内网络的要挂代理下载，看[ReadMe](https://github.com/tylearymf/UniHacker/blob/main/README.md)
