### ISSUE TITLE
2021.3.10f1 (ARM64) macos M1 not supported

### ISSUE THREAD

**Issue by nikib251** [tylearymf/UniHacker#66]
![msg46190332-57905](https://user-images.githubusercontent.com/107720417/194025696-e22415aa-225b-48fa-b6c0-c66e286ac86e.jpg)
downloaded from unity hub

**Comment by tylearymf** [comment]
https://drive.google.com/file/d/1E7IudYf_D5d6uLAES9ezlhS8fKEMbqUA/view?usp=sharing
@nikib251 Try this beta version.
