### ISSUE TITLE
Window Build v3.8 will be removed by Microsoft Defender

### ISSUE THREAD

**Issue by raku10dev** [tylearymf/UniHacker#68]
Hi
Build v3.8 will be removed after downloaded by Microsoft Defender (Because virus detected). There are no problems on v3.7 build.
Can you check it again ?
Thank you

**Comment by tylearymf** [comment]
@raku10dev The latest version doesn't have some special code, so you might have to trust it, or you can try clone and build it

**Comment by raku10dev** [comment]
@tylearymf 
Thank you for you reply !
But what I mean is when building version 3.8, did you forget to set something to let windows defender misunderstand that it contains a virus. Because I don't see it when I download version 3.7.

**Comment by tylearymf** [comment]
> @tylearymf Thank you for your reply ! But what I mean is when building version 3.8, Did you forget to set something to let windows defender misunderstand that it contains a virus ?. Because I don't see it when I download version 3.7.

I use the custom scan of the Defender of multiple computers, and the result does not have any virus. My OS is Win10 21H2.
![image](https://user-images.githubusercontent.com/14980389/194790531-ebe8f41b-7332-4706-a259-8554e4b20671.png)
![image](https://user-images.githubusercontent.com/14980389/194790714-778bbb31-b52f-4162-97bf-30e973ecfd62.png)
