### ISSUE TITLE
2022.2.0b10 not support

### ISSUE THREAD

**Issue by liuliehuan** [tylearymf/UniHacker#69]
2022.0.0b10 not support

**Comment by tylearymf** [comment]
Unity没有这个版本

**Comment by alexuhui** [comment]
https://unity3d.com/cn/beta/2022.2b   这算不算重定向到了国内？

**Comment by tylearymf** [comment]
> 预发行版有，确实不支持

我只看到 2022.2.0b10 这个版本

**Comment by tylearymf** [comment]
> https://unity3d.com/cn/beta/2022.2b 这算不算重定向到了国内？

算吧

**Comment by alexuhui** [comment]
哦哦，可能是他打错了？那访问这个应该就是对的   https://unity3d.com/beta/2022.2b

**Comment by tylearymf** [comment]
@liuliehuan @alexuhui 2022.2.0版本开始，Unity已经重构了License认证逻辑了，目前还没有办法破解。

**Comment by alexuhui** [comment]
> @liuliehuan @alexuhui 2022.2.0版本开始，Unity已经重构了License认证逻辑了，目前还没有办法破解。

好的。辛苦了。我只是想看看Entitie 1.0的例子而已

**Comment by RouderSky** [comment]
> @liuliehuan @alexuhui 2022.2.0版本开始，Unity已经重构了License认证逻辑了，目前还没有办法破解。

还有破解的可能吗

**Comment by tylearymf** [comment]
> > @liuliehuan @alexuhui 2022.2.0版本开始，Unity已经重构了License认证逻辑了，目前还没有办法破解。
> 
> 还有破解的可能吗

目前还没时间去捣鼓这个

**Comment by Subfire** [comment]
版本:2019.4.37f1c1 (X64) ⇒ 国内特供版不支持破解

**Comment by freepik19** [comment]
English Please

**Comment by TriggerEdge** [comment]
> English Please

Just use google translator
