### ISSUE TITLE
2017.4.40.7214086 无法破解

### ISSUE THREAD

**Issue by kane9527-e** [tylearymf/UniHacker#7]
![image](https://user-images.githubusercontent.com/9569527/168475331-1cc2f303-0b9f-4237-a95e-0ca2214c7bfd.png)

**Comment by tylearymf** [comment]
![image](https://user-images.githubusercontent.com/14980389/168475917-789021c0-e8e6-460d-810a-b9f3327eb31f.png)
![image](https://user-images.githubusercontent.com/14980389/168475945-be0dfaaf-e87d-41cf-aa3c-3f36931695f7.png)
你下载的版本有问题

**Comment by tylearymf** [comment]
你可以对比下文件大小

**Comment by kane9527-e** [comment]
![image](https://user-images.githubusercontent.com/9569527/168476248-ebfc38b5-1ccd-4aea-99f2-42cc4c9d1c92.png)
.com官网hub下载的,为啥大小不一样

**Comment by kane9527-e** [comment]
hub下载的不行,网页下载的可以了
