### ISSUE TITLE
Unity2019.4.40f0  Mac(Intel) not support 

### ISSUE THREAD

**Issue by xujingfire** [tylearymf/UniHacker#70]
Unity2019.4.40f0  Mac(Intel) not support

**Comment by xujingfire** [comment]
是不是2019.4.X都不行呀，我刚才下载了一个4.38也不支持

**Comment by tylearymf** [comment]
> 是不是2019.4.X都不行呀，我刚才下载了一个4.38也不支持

前几天提交的代码有问题🤣

**Comment by tylearymf** [comment]
@xujingfire 我重新编译了个3.8版本，下载试试 [3.8版本](https://github.com/tylearymf/UniHacker/releases/tag/3.8)

**Comment by xujingfire** [comment]
![image](https://user-images.githubusercontent.com/16539286/195125951-1f623478-a30a-40f4-9233-fde1762814c1.png)
这次可以了

**Comment by RiverZeng92** [comment]
Unity2019.4.31f1 失败

**Comment by tylearymf** [comment]
> Unity2019.4.31f1 失败

截个图看看
