### ISSUE TITLE
2020.3.25f1无法修改

### ISSUE THREAD

**Issue by misaka10843** [tylearymf/UniHacker#71]
![image](https://user-images.githubusercontent.com/69132853/195301921-61fc3eab-a602-493d-b076-711f3c2a272c.png)
已全程挂全局梯，不存在国内特供（除非2020以前的版本没有fxcx的命名方式以及unity3d.com官网放的cn包）

**Comment by tylearymf** [comment]
@misaka10843 卸载掉你下载的，然后浏览器里打开这个试试：unityhub://2020.3.25f1/9b9180224418

**Comment by misaka10843** [comment]
> unityhub://2020.3.25f1/9b9180224418

还是不行🤣

**Comment by tylearymf** [comment]
那你用IDM+Proxifier下载下**国际版**的这个地址的.
国际版：https://download.unity3d.com/download_unity/9b9180224418/Windows64EditorInstaller/UnitySetup64-2020.3.25f1.exe
国内版：https://download.unitychina.cn/download_unity/9b9180224418/Windows64EditorInstaller/UnitySetup64-2020.3.25f1.exe

如果没挂代理，IDM地址栏会自动转换成国内版地址的。
[IDM下载地址](https://mirror2.internetdownloadmanager.com/idman641build3.exe?v=lt&filename=idman641build3.exe)
[Proxifier下载地址](https://www.proxifier.com/download/ProxifierSetup.exe)

**Comment by misaka10843** [comment]
![image](https://user-images.githubusercontent.com/69132853/195318122-fc0719d0-c88b-47a1-b85e-0244e49a1e83.png)
尝试下过，还是不行

**Comment by tylearymf** [comment]
不行是指还是显示特供版吗，如果是显示特供版那就是你没代理到

**Comment by misaka10843** [comment]
> 不行是指还是显示特供版吗，如果是显示特供版那就是你没代理到

复制出来的链接是3d.com

![image](https://user-images.githubusercontent.com/69132853/195319959-d45b3fb9-9bf5-4d3f-aa95-c8eb394eef8c.png)

**Comment by misaka10843** [comment]
在同一网络环境下，使用hub下载的编辑器，2020.3.40f1可以正常修改，但是2020.3.25f1不行

**Comment by Z-fly** [comment]
试过2020.3.25f1的后一个更新版本吗？

**Comment by tylearymf** [comment]
@misaka10843 
![image](https://user-images.githubusercontent.com/14980389/195349057-02c3b10f-9cb3-4f68-b861-7c18ed57bc3d.png)

**Comment by tylearymf** [comment]
![image](https://user-images.githubusercontent.com/14980389/195349188-37ece0ef-b524-4593-a0b8-c1991267360a.png)

**Comment by tylearymf** [comment]
@misaka10843 你的代理有问题

**Comment by misaka10843** [comment]
> @misaka10843 你的代理有问题

可能吧🤣

已经换成可以修改的2020版本了🤣
