### ISSUE TITLE
Linux Kubuntu 22.04 Unity 2021.3.11f1 Linux Kernel 5.15.0-50-generic

### ISSUE THREAD

**Issue by reidsneo** [tylearymf/UniHacker#73]
Unity3D binary was patched but still display
No valid unity editor license found. Please activate your license
![image](https://user-images.githubusercontent.com/12298979/195878170-c3bad1c6-7f30-4196-8478-a3b7c22e2107.png)

**Comment by tylearymf** [comment]
![image](https://user-images.githubusercontent.com/14980389/195979420-25de4d59-6ce9-4bef-bab2-60bb42499ff9.png)
@reidsneo Did you crack Unity Hub?

**Comment by reidsneo** [comment]
![image](https://user-images.githubusercontent.com/12298979/195990540-faf15e1d-dc60-48b3-bfd8-c3ffdf615552.png)

@tylearymf Hi, yes already patched, I also tried different approach, using anonym or personal account both is wont working
any suggestion?

**Comment by tylearymf** [comment]
@reidsneo You can try to revert the hub and unity and then patch.

**Comment by tylearymf** [comment]
![image](https://user-images.githubusercontent.com/14980389/195996713-eb93f099-0dd1-4161-aa61-8dc7f4defa45.png)

**Comment by reidsneo** [comment]
Unfortunately still not working, maybe I need to downgrade the unity version matched with your.
for unityhub did you use from apt or from appimage?

**Comment by tylearymf** [comment]
> Unfortunately still not working, maybe I need to downgrade the unity version matched with your. for unityhub did you use from apt or from appimage?

apt

**Comment by tylearymf** [comment]
@reidsneo Maybe you can try uninstall unity hub.

**Comment by reidsneo** [comment]
Reinstalling both unity and unityhub no dice, still display this message "No valid unity editor license found. Please activate your license"
:(

**Comment by tylearymf** [comment]
> Reinstalling both unity and unityhub no dice, still display this message "No valid unity editor license found. Please activate your license" :(

I have time to install Kubuntu 22.04, then check your question.

**Comment by reidsneo** [comment]
> > Reinstalling both unity and unityhub no dice, still display this message "No valid unity editor license found. Please activate your license" :(
> 
> I have time to install Kubuntu 22.04, then check your question.

Thank you for the support & time :)

**Comment by tylearymf** [comment]
Hi, @reidsneo , I installed Unity2021.3.11f1 and UnityHub3.3.0 on kubuntu on the virtual machine, and they both work well. I guess you can't open Unity, maybe there is something wrong with your kubuntu environment?

![image](https://user-images.githubusercontent.com/14980389/198201347-9bfc824a-5893-4894-a35b-10ded774a47e.png)

**Comment by reidsneo** [comment]
It seem something prevent me to make the license key
```
2022-10-20 07:38:06.833 - WARN  - Unity.Licensing.Client.Configuration.PathProviders.PathProviderUtility || license directory /home/myuserid/.config/unity3d/Unity/licenses not found
2022-10-20 07:38:06.833 - INFO  - Unity.Licensing.Client.Configuration.PathProviders.PathProviderUtility || Searching for legacy license file: /home/myuserid/.config/unity3d/Unity/Unity_lic.ulf
2022-10-20 07:38:06.833 - WARN  - Unity.Licensing.Client.Configuration.PathProviders.PathProviderUtility || Legacy license file not found: /home/myuserid/.config/unity3d/Unity/Unity_lic.ulf
2022-10-20 07:38:06.833 - WARN  - Unity.Licensing.Client.Configuration.PathProviders.PathProviderUtility || license directory /usr/share/unity3d/licenses not found
2022-10-20 07:38:06.833 - INFO  - Unity.Licensing.Client.Configuration.PathProviders.PathProviderUtility || Searching for legacy license file: /usr/share/unity3d/Unity_lic.ulf
2022-10-20 07:38:06.833 - WARN  - Unity.Licensing.Client.Configuration.PathProviders.PathProviderUtility || Legacy license file not found: /usr/share/unity3d/Unity_lic.ulf
2022-10-20 07:38:06.834 - WARN  - Unity.Licensing.Client.Configuration.PathProviders.PathProviderUtility || license directory /home/myuserid/.local/share/unity3d/Unity/licenses not found
2022-10-20 07:38:06.834 - INFO  - Unity.Licensing.Client.Configuration.PathProviders.PathProviderUtility || Searching for legacy license file: /home/myuserid/.local/share/unity3d/Unity/Unity_lic.ulf
2022-10-20 07:38:06.834 - INFO  - Unity.Licensing.Client.Configuration.PathProviders.PathProviderUtility || Found legacy license file: /home/myuserid/.local/share/unity3d/Unity/Unity_lic.ulf
2022-10-20 07:38:07.070 - INFO  - Unity.Licensing.Client.Services.Helpers.LicenseFilesMapper || Successfully parsed (legacy) license /home/myuserid/.local/share/unity3d/Unity/Unity_lic.ulf
```
But when using legit unityhub and generate personal license it working good
do you mind to share the Unity_lic.ulf file?
/home/myuserid/.local/share/unity3d/Unity/Unity_lic.ulf

**Comment by tylearymf** [comment]
> It seem something prevent me to make the license key
> 
> ```
> 2022-10-20 07:38:06.833 - WARN  - Unity.Licensing.Client.Configuration.PathProviders.PathProviderUtility || license directory /home/myuserid/.config/unity3d/Unity/licenses not found
> 2022-10-20 07:38:06.833 - INFO  - Unity.Licensing.Client.Configuration.PathProviders.PathProviderUtility || Searching for legacy license file: /home/myuserid/.config/unity3d/Unity/Unity_lic.ulf
> 2022-10-20 07:38:06.833 - WARN  - Unity.Licensing.Client.Configuration.PathProviders.PathProviderUtility || Legacy license file not found: /home/myuserid/.config/unity3d/Unity/Unity_lic.ulf
> 2022-10-20 07:38:06.833 - WARN  - Unity.Licensing.Client.Configuration.PathProviders.PathProviderUtility || license directory /usr/share/unity3d/licenses not found
> 2022-10-20 07:38:06.833 - INFO  - Unity.Licensing.Client.Configuration.PathProviders.PathProviderUtility || Searching for legacy license file: /usr/share/unity3d/Unity_lic.ulf
> 2022-10-20 07:38:06.833 - WARN  - Unity.Licensing.Client.Configuration.PathProviders.PathProviderUtility || Legacy license file not found: /usr/share/unity3d/Unity_lic.ulf
> 2022-10-20 07:38:06.834 - WARN  - Unity.Licensing.Client.Configuration.PathProviders.PathProviderUtility || license directory /home/myuserid/.local/share/unity3d/Unity/licenses not found
> 2022-10-20 07:38:06.834 - INFO  - Unity.Licensing.Client.Configuration.PathProviders.PathProviderUtility || Searching for legacy license file: /home/myuserid/.local/share/unity3d/Unity/Unity_lic.ulf
> 2022-10-20 07:38:06.834 - INFO  - Unity.Licensing.Client.Configuration.PathProviders.PathProviderUtility || Found legacy license file: /home/myuserid/.local/share/unity3d/Unity/Unity_lic.ulf
> 2022-10-20 07:38:07.070 - INFO  - Unity.Licensing.Client.Services.Helpers.LicenseFilesMapper || Successfully parsed (legacy) license /home/myuserid/.local/share/unity3d/Unity/Unity_lic.ulf
> ```
> 
> But when using legit unityhub and generate personal license it working good do you mind to share the Unity_lic.ulf file? /home/myuserid/.local/share/unity3d/Unity/Unity_lic.ulf

The ulf file is automatically generated after patch unity, maybe there is a problem with your local ulf folder permissions?

**Comment by reidsneo** [comment]
I triple check the permission and ownership it is good, but still no dice, thank you for your support
I will consider this is the environment issue instead of the patcher issue, feel free to close the issue

Thank you!

**Comment by tylearymf** [comment]
> I triple check the permission and ownership it is good, but still no dice, thank you for your support I will consider this is the environment issue instead of the patcher issue, feel free to close the issue
> 
> Thank you!

You can use this license file, you can modify the <Update Time> tag or <Feature> tag in the file
[Unity_lic.zip](https://github.com/tylearymf/UniHacker/files/9899519/Unity_lic.zip)

**Comment by tylearymf** [comment]
@reidsneo Try this beta version. https://drive.google.com/file/d/1bwi1y7D1YY5B9zM39dXet7ndCvToOyaY/view?usp=share_link

**Comment by reidsneo** [comment]
> > I triple check the permission and ownership it is good, but still no dice, thank you for your support I will consider this is the environment issue instead of the patcher issue, feel free to close the issue
> > Thank you!
> 
> You can use this license file. If you are going to use a personal license, remember to backup this file. [Unity_lic.zip](https://github.com/tylearymf/UniHacker/files/9899519/Unity_lic.zip)

![image](https://user-images.githubusercontent.com/12298979/199137938-97ecd0a8-5f8c-4530-8428-ad927e076c68.png)
I patched the unity using UniHackerV3.8.AppImage patcher, and after that copy manually the pro license to the local share config path
and it is working, what I assume is correct, the key was not generated after applied the patch
one moment I will try the beta version

**Comment by reidsneo** [comment]
> @reidsneo Try this beta version. https://drive.google.com/file/d/1bwi1y7D1YY5B9zM39dXet7ndCvToOyaY/view?usp=share_link
This one is working good!
The beta fix my issue here is the summary :
 - UniHackerV3.8.AppImage : 
      - patching binary is working good, but having issue while creating Unity_lic.ulf in config folder
      - restore patching binary is working good, it revert back to normal BUT while having Unity_lic.ulf  in config folder, this is not removed

 - UniHackerV3.8.1.AppImage (beta version) :
      - Patching binary is working good, license file is created in config directory
      - Restoring patched binary to normal working good, license file in config directory also deleted
      
 Bravo!!
