### ISSUE TITLE
Mac M1 Unity 2021 LTS版 无法破解

### ISSUE THREAD

**Issue by Cowboy-Shuai** [tylearymf/UniHacker#75]
### **Mac M1 Unity 2021.3.11f1c2 LTS版 无法破解**
![screenshot-20221017-233525](https://user-images.githubusercontent.com/19619031/196220689-1c787991-f87b-484d-ae13-04cf418437af.png)

**UnityHub：Unity Hub 3.3.0-c3**

![screenshot-20221017-232731](https://user-images.githubusercontent.com/19619031/196219462-5acf684a-8314-4918-8f5f-d53a7999daaf.png)

**Unity：2021.3.11f1c2 (ARM64)**

![screenshot-20221017-232645](https://user-images.githubusercontent.com/19619031/196219644-196d51f4-23bd-4d3e-b024-7c5df8857ded.png)

**UniHacker：3.8**

![screenshot-20221017-232606](https://user-images.githubusercontent.com/19619031/196219760-7bcea26b-ba09-4e45-b604-d79ccef72246.png)

**MacOS：12.2.1** 

![screenshot-20221017-233858](https://user-images.githubusercontent.com/19619031/196221465-d912967f-9fd5-4426-9efa-981f7ce38165.png)

**Comment by tylearymf** [comment]
@Cowboy-Shuai 你下载的是国内版本(带c1、c2结尾的)，不支持的，去这个地址下载试试
Github 国际版下载地址：https://github.com/AlianBlank/download.unity.com

**Comment by Cowboy-Shuai** [comment]
@tylearymf 是的，UnityHub也是带c3，可能下载的时候下载器没有走全局代理 下载到了特供版的UnityHub了，重新下载安装好国际版本的Unity和UnityHub就可以了！感谢🙏
