### ISSUE TITLE
麻烦问下m1的Mac mini 2022.1的unity版本能破解吗

### ISSUE THREAD

**Issue by yuqwert123** [tylearymf/UniHacker#76]

**Comment by tylearymf** [comment]
可以的

**Comment by yuqwert123** [comment]
报这个错误呢License error

**Comment by yuqwert123** [comment]
unity破解了打不开

**Comment by tylearymf** [comment]
提供下具体unity版本和unityhub的版本，可以截图

**Comment by yuqwert123** [comment]
unity Hub3.3.0 (X64).   unity 2022.1.1f1 (ARM64

**Comment by yuqwert123** [comment]
![091AF3B2-CBDD-4D88-A1AD-A31FCBE70EEF](https://user-images.githubusercontent.com/116050206/196333425-09058b23-e508-49fa-89e5-f4b74ac487be.png)

**Comment by yuqwert123** [comment]
![87D1F14E-893D-456B-BD5B-3DA10AF09864](https://user-images.githubusercontent.com/116050206/196333504-646b3485-e78f-4614-9a6e-0dc33746a8fc.png)

**Comment by tylearymf** [comment]
@yuqwert123 用你下载的UnHacker软件，选Unity.app，然后点Revert，再用下面的版本执行下Patch试试
https://wwt.lanzouv.com/iuYJ10e3hgpg

**Comment by yuqwert123** [comment]
![38E8B27A-E5E6-49FC-A626-496B3ED665BE](https://user-images.githubusercontent.com/116050206/196359925-c8da095b-fe29-4646-a33c-b5e908e8b8db.png)
这个版本没有恢复按钮呢

**Comment by yuqwert123** [comment]
感谢大佬。多次尝试可以了
