### ISSUE TITLE
关于Legacy License移除后的验证逻辑重构

### ISSUE THREAD

**Issue by Soneoylys** [tylearymf/UniHacker#78]
在2022.2以上版本的Editor中, Legacy License认证逻辑似乎被完全移除了, 是否应该考虑通过手动还原被移除的函数的方式来恢复破解的可能性; 而或是寻找其他可行方案?

**Comment by tylearymf** [comment]
> 在2022.2以上版本的Editor中, Legacy License认证逻辑似乎被完全移除了, 是否应该考虑通过手动还原被移除的函数的方式来恢复破解的可能性; 而或是寻找其他可行方案?

还原被移除的函数，这个是不可能的了，只能花点时间慢慢找对应的函数了，目前是能破解进去Unity了，但是显示不是Pro版本的，所以后面有空我再看看了

**Comment by Soneoylys** [comment]
> 还原被移除的函数，这个是不可能的了，只能花点时间慢慢找对应的函数了，目前是能破解进去Unity了，但是显示不是Pro版本的，所以后面有空我再看看了

感谢回复, 方便提供大致查找思路吗 例如自检的具体函数名, 我有时间也可以顺着尝试找找看

**Comment by Soneoylys** [comment]
> @Soneoylys https://wwt.lanzouv.com/iNIWF0e3ymti

谢谢您的资料, 使用x64dbg这种调试工具确实比用Hopper或Ghidra进行静态分析更方便
在尝试修改了2022.2.0b9及2022.2.0b11后, 发现貌似并不能成功启动Patch过的文件, 以下是两个版本的具体表现
b9版本仍尝试唤起Licensing Client, 之后自动结束进程, Editor同时自行退出
b11版本跳出错误窗口后迅速结束进程, 但没有尝试启动Licensing Client
已经确认所修改的Hex正确且没有offset错误 以上两个错误结束速度太快以至于无法抓到断点进行分析

我的时区在-8 可能无法及时回复issue, 如果我有进一步的发现 将在这里追加信息

**Comment by tylearymf** [comment]
> > @Soneoylys https://wwt.lanzouv.com/iNIWF0e3ymti
> 
> 谢谢您的资料, 使用x64dbg这种调试工具确实比用Hopper或Ghidra进行静态分析更方便 在尝试修改了2022.2.0b9及2022.2.0b11后, 发现貌似并不能成功启动Patch过的文件, 以下是两个版本的具体表现 b9版本仍尝试唤起Licensing Client, 之后自动结束进程, Editor同时自行退出 b11版本跳出错误窗口后迅速结束进程, 但没有尝试启动Licensing Client 已经确认所修改的Hex正确且没有offset错误 以上两个错误结束速度太快以至于无法抓到断点进行分析
> 
> 我的时区在-8 可能无法及时回复issue, 如果我有进一步的发现 将在这里追加信息

忘了跟你说了，要手动将 Editor\Data\Resources\Licensing\Client\Unity.Licensing.Client.exe 改名为 Unity.Licensing.Client.exe.bak 再断点调试。

**Comment by Soneoylys** [comment]
> 忘了跟你说了，要手动将 Editor\Data\Resources\Licensing\Client\Unity.Licensing.Client.exe 改名为 Unity.Licensing.Client.exe.bak 再断点调试。

已经修改成功, 静态分析后发现读入Pro的验证逻辑似乎使用了栈里的内容, 正在考虑是否是Licensing Client传入的
此外, 如果栈中有Licensing Client启动后生成的"脏数据", Editor似乎会直接Crash, 可能也是上面提到函数的问题
具体表现为修改后仍无法启动, 直到系统进行完全重启

**Comment by tylearymf** [comment]
> > 忘了跟你说了，要手动将 Editor\Data\Resources\Licensing\Client\Unity.Licensing.Client.exe 改名为 Unity.Licensing.Client.exe.bak 再断点调试。
> 
> 已经修改成功, 静态分析后发现读入Pro的验证逻辑似乎使用了栈里的内容, 正在考虑是否是Licensing Client传入的 此外, 如果栈中有Licensing Client启动后生成的"脏数据", Editor似乎会直接Crash, 可能也是上面提到函数的问题 具体表现为修改后仍无法启动, 直到系统进行完全重启

目前我清楚的是：LicensingClient与Unity间的通讯是明文的json数据，可以看看SendRequest这个函数，不过貌似有保护，我想的是直接hook掉这个函数 licensing::Module::HasEntitlements，让其默认返回一个固定结构对象，但是目前还不清楚EntitlementResultMap里面的结构

**Comment by Soneoylys** [comment]
> 目前我清楚的是：LicensingClient与Unity间的通讯是明文的json数据，可以看看SendRequest这个函数，不过貌似有保护，我想的是直接hook掉这个函数 licensing::Module::HasEntitlements，让其默认返回一个固定结构对象，但是目前还不清楚EntitlementResultMap里面的结构

是否应该考虑从Licensing Client入手? 导入debug后发现网络上报验证许可证的操作, 或许可以在关闭证书检查后通过网络重放跳过检查下发正确的json, 使用的证书类型是RSA4096, 加密方案是SHA384, 域名硬编码进了Binary, hook这个也许更方便

**Comment by tylearymf** [comment]
> > 目前我清楚的是：LicensingClient与Unity间的通讯是明文的json数据，可以看看SendRequest这个函数，不过貌似有保护，我想的是直接hook掉这个函数 licensing::Module::HasEntitlements，让其默认返回一个固定结构对象，但是目前还不清楚EntitlementResultMap里面的结构
> 
> 是否应该考虑从Licensing Client入手? 导入debug后发现网络上报验证许可证的操作, 或许可以在关闭证书检查后通过网络重放跳过检查下发正确的json, 使用的证书类型是RSA4096, 加密方案是SHA384, 域名硬编码进了Binary, hook这个也许更方便

Client好像加了vm保护，你可以试试能不能改

**Comment by Soneoylys** [comment]
> Client好像加了vm保护，你可以试试能不能改

是的 看起来被摆了一道, 我尝试用Debugger找OEP, 但是被Kernal32的一个Detect Debugger方法给弹出去了, 有个百试百灵的方法是用QEMU+GDB, 不过看样子这个Client主程序唤起了其他线程, 如果去追的话还要考虑Dump出的内存里存在太多无用数据查找麻烦的问题, 误判了工作量, 这样看起来还是继续追现成的函数相对没那么复杂

**Comment by Soneoylys** [comment]
> 还原被移除的函数，这个是不可能的了，只能花点时间慢慢找对应的函数了，目前是能破解进去Unity了，但是显示不是Pro版本的，所以后面有空我再看看了

找到一个新问题, 在导入Package的时候, Package Manager会提示 "The following packages were not registered because your license doesn't allow it." 目前暂未找到解决方案, 考虑是因为未找到license时无法安装任何Package

**Comment by tylearymf** [comment]
> > 还原被移除的函数，这个是不可能的了，只能花点时间慢慢找对应的函数了，目前是能破解进去Unity了，但是显示不是Pro版本的，所以后面有空我再看看了
> 
> 找到一个新问题, 在导入Package的时候, Package Manager会提示 "The following packages were not registered because your license doesn't allow it." 目前暂未找到解决方案, 考虑是因为未找到license时无法安装任何Package

是的，需要在某个地方填充个license数据进去

**Comment by kxn** [comment]
> > > 忘了跟你说了，要手动将 Editor\Data\Resources\Licensing\Client\Unity.Licensing.Client.exe 改名为 Unity.Licensing.Client.exe.bak 再断点调试。
> > 
> > 
> > 已经修改成功, 静态分析后发现读入Pro的验证逻辑似乎使用了栈里的内容, 正在考虑是否是Licensing Client传入的 此外, 如果栈中有Licensing Client启动后生成的"脏数据", Editor似乎会直接Crash, 可能也是上面提到函数的问题 具体表现为修改后仍无法启动, 直到系统进行完全重启
> 
> 目前我清楚的是：LicensingClient与Unity间的通讯是明文的json数据，可以看看SendRequest这个函数，不过貌似有保护，我想的是直接hook掉这个函数 licensing::Module::HasEntitlements，让其默认返回一个固定结构对象，但是目前还不清楚EntitlementResultMap里面的结构

一般来说如果遇到有保护，可以去看看mac版本的静态逆向，也许能做个 fake client ？

**Comment by Soneoylys** [comment]
> > 目前我清楚的是：LicensingClient与Unity间的通讯是明文的json数据，可以看看SendRequest这个函数，不过貌似有保护，我想的是直接hook掉这个函数 licensing::Module::HasEntitlements，让其默认返回一个固定结构对象，但是目前还不清楚EntitlementResultMap里面的结构
> 
> 一般来说如果遇到有保护，可以去看看mac版本的静态逆向，也许能做个 fake client ？

我对静态分析Client不报乐观态度, 不过如果用QEMU+GDB打断点找OEP之后脱壳出VMP的话, 也许可以试试看
不过如果脱壳了之后我是更倾向于直接改而不是逆向通信协议
在没有脱壳的情况下要去逆向通信协议是比现有思路更困难的

**Comment by BluBb-mADe** [comment]
根据我的了解，Mac上的整个认证/许可证过程机制不同，因此，即使您成功逆向工程了Mac上的许可证过程，我也不确定结果会对Windows客户端有所帮助。

**Comment by AfarMiss** [comment]
之前我修改之前的版本方式是修改UnityConnect::Get()+0x64A1 SetILicensing为Legacy
WinMain->ILicensing::BootstrapLicensing->InitializeModule_Licensing->SetILicensing

因为不清楚EntitlementResultMap结构
所有调用Licensing::Module::HasEntitlementsInternal的地方返回的EntitlementResultMap
ecx+0x50改为1
注意ILicensing::EntitlementResultMap::operator[]也要修改
但是只能跳过许可证无效,显示并非pro版

理论知道EntitlementResultMap的情况下在源头修改即可为pro版

**Comment by tylearymf** [comment]
> 之前我修改之前的版本方式是修改UnityConnect::Get()+0x64A1 SetILicensing为Legacy WinMain->ILicensing::BootstrapLicensing->InitializeModule_Licensing->SetILicensing
> 
> 因为不清楚EntitlementResultMap结构 所有调用Licensing::Module::HasEntitlementsInternal的地方返回的EntitlementResultMap ecx+0x50改为1 注意ILicensing::EntitlementResultMap::operator[]也要修改 但是只能跳过许可证无效,显示并非pro版
> 
> 理论知道EntitlementResultMap的情况下在源头修改即可为pro版

嗯，谢谢你的修改思路。

**Comment by jiongge** [comment]
qq群有个网友说的，我是不懂，看看是不是新思路，我看他用的2022.2.1f1就是pro：2022.2的破解方法很简单的，其实就是dll的破解，验证都放在unityhub，unityhub又依赖unitylicenseclient.exe，找到dll关键的验证是否有效证书的函数，把里面false全改成true就好了

**Comment by soft2005168** [comment]
也就是说安装新版本就必须安装unityhub了吗

**Comment by tylearymf** [comment]
> 也就是说安装新版本就必须安装unityhub了吗

hub本来就很好用呀，为啥不装

**Comment by GaaraZhaoUnity** [comment]
2021.3.19f1也已经不能破解了。

**Comment by CODING-GHOST** [comment]
2021.3.19f1也已经不能破解了
好像真的是哦

**Comment by GaaraZhaoUnity** [comment]
新的一版4.3可以2021.3.19f1了

**Comment by truethor** [comment]
能不能通过修改 Licensing.Client 返回一个可以通过验证的数据，或者两边配合一下有没有希望？

**Comment by soft2005168** [comment]
2022.2.x和2023.x版本可以了吗

**Comment by agiknight** [comment]
2020.3.46启动失败

**Comment by tylearymf** [comment]
> 2020.3.46,2020.3.45启动失败

嗯，晚点发个版本

**Comment by YueWangChen** [comment]
2022.2.x和2023.x我有破解方案 让其可以加载许可证

**Comment by tylearymf** [comment]
> 2022.2.x和2023.x我有破解方案 让其可以加载许可证

细说

**Comment by YueWangChen** [comment]
![21](https://user-images.githubusercontent.com/22950290/224874711-ab48aa8d-fbd6-4575-b2d4-6576361f6906.jpg)
这样

**Comment by tylearymf** [comment]
> ![21](https://user-images.githubusercontent.com/22950290/224874711-ab48aa8d-fbd6-4575-b2d4-6576361f6906.jpg) 这样

这么牛，有意愿分享吗

**Comment by YueWangChen** [comment]
![GIF](https://user-images.githubusercontent.com/22950290/224876204-e4d35b7b-b827-4231-8cdf-e920466f30fb.gif)
完全正常使用

**Comment by tylearymf** [comment]
> ![GIF](https://user-images.githubusercontent.com/22950290/224876204-e4d35b7b-b827-4231-8cdf-e920466f30fb.gif)完全正常使用

666

**Comment by YueWangChen** [comment]
![GIF](https://user-images.githubusercontent.com/22950290/224886194-3ec3d3ab-1e0d-4f94-b753-45b730b80235.gif)
CN版本也正常

**Comment by LiuOcean** [comment]
啥流程啊老哥，pr 到仓库来呗。

**Comment by YueWangChen** [comment]
![29](https://user-images.githubusercontent.com/22950290/224887870-48bd6f2f-f195-4e1c-b482-e97e833c703e.jpg)
还有 Mac

**Comment by soft2005168** [comment]
YueWangChen可以分享吗

**Comment by YueWangChen** [comment]
![GIF](https://user-images.githubusercontent.com/22950290/224895728-e434fac2-661e-4b85-a585-2b8089d368a3.gif)
Mac端破解正常

**Comment by YueWangChen** [comment]
破解掉签名校验，就可以了

**Comment by truethor** [comment]
22.2可以破解了？ 什么时候更新？

**Comment by lileifree** [comment]
> 破解掉签名校验，就可以了

666

**Comment by Soneoylys** [comment]
> 破解掉签名校验，就可以了

方便提供具体操作方式吗，例如hook什么函数，如何inject证书等

**Comment by yc2768** [comment]
> ![GIF](https://user-images.githubusercontent.com/22950290/224895728-e434fac2-661e-4b85-a585-2b8089d368a3.gif) [ ![GIF](https://user-images.githubusercontent.com/22950290/224895728-e434fac2-661e-4b85-a585-2b8089d368a3.gif) ](https://user-images.githubusercontent.com/22950290/224895728-e434fac2-661e-4b85-a585-2b8089d368a3.gif) [ ](https://user-images.githubusercontent.com/22950290/224895728-e434fac2-661e-4b85-a585-2b8089d368a3.gif) Mac端破解正常

大佬能把这个版本的补丁分享出来给我们用一下吗

**Comment by YueWangChen** [comment]
![GIF 2023-3-30 17-17-06](https://user-images.githubusercontent.com/22950290/228789951-1a9821b1-f6cd-477e-8680-ea81c56bde3c.gif)
2023.2.0a8破解正常

**Comment by soft2005168** [comment]
@YueWangChen:能分享一下吗；

**Comment by YueWangChen** [comment]
![S_12-56-58](https://user-images.githubusercontent.com/22950290/229026540-6e308a23-594b-4cb2-969d-fd73a6a4eee4.png)
Ubuntu破解没问题

**Comment by YueWangChen** [comment]
![GIF 2023-3-31 14-24-04](https://user-images.githubusercontent.com/22950290/229041179-27cf88a5-6f80-4556-9991-d2e424212044.gif)
Unbuntu 中国版2022.2.12f1c1破解正常

**Comment by iisgy2016** [comment]
厉害了，能分享下就更好

**Comment by grapefruitlips** [comment]
YueWangChen, 请分享破解方法

**Comment by iisgy2016** [comment]
大佬这么多，有人能分享下？

**Comment by MemoChen** [comment]
> ![动图 2023-3-31 14-24-04](https://user-images.githubusercontent.com/22950290/229041179-27cf88a5-6f80-4556-9991-d2e424212044.gif) [ ![GIF 2023-3-31 14-24-04](https://user-images.githubusercontent.com/22950290/229041179-27cf88a5-6f80-4556-9991-d2e424212044.gif) ](https://user-images.githubusercontent.com/22950290/229041179-27cf88a5-6f80-4556-9991-d2e424212044.gif) [ ](https://user-images.githubusercontent.com/22950290/229041179-27cf88a5-6f80-4556-9991-d2e424212044.gif) Unbuntu 中国版2022.2.12f1c1破解正常
大佬可以分享一下吗，学习学习

**Comment by scc172fly** [comment]
怎么这么久了还没更上来呀？中国版Unity都能破了？这么牛逼的么？

**Comment by soft2005168** [comment]
什么时候更新一下破解呢，这么多高手在这里留言

**Comment by lileifree** [comment]
个人觉得像@YueWangChen这样只截图不分享方法的，可以ignore了，没什么实际的作用。

**Comment by YueWangChen** [comment]
这是急坏了嘛

**Comment by williambrkn** [comment]
> 个人觉得像@YueWangChen这样只截图不分享方法的，可以ignore了，没什么实际的作用。

他只是拿群里的截图来炫耀下，又不是他破解的，他也很急等着群里的大佬放出呢

**Comment by zhcrxn** [comment]
大家都等等吧，现在破解版放出来了过几天验证方式又变了，那不是白忙活了，过段时间稳定了肯定有人放，今天我也知道破解方法了，功能都没问题，其实破解方法很简单

**Comment by YueWangChen** [comment]
独乐了不如众乐乐 可以到我的GitHub上 已经开放出来了

**Comment by YueWangChen** [comment]
一群鸟人 服了吧

**Comment by YueWangChen** [comment]
TMD

**Comment by soft2005168** [comment]
我看大家都折服了

**Comment by YueWangChen** [comment]
这起码可以破解到Unity2024

**Comment by soft2005168** [comment]
我们力挺你@YueWangChen

**Comment by YueWangChen** [comment]
CN版需要2023年3月以后发布的版本，之前的目前无法破解

**Comment by chumomo** [comment]
> CN版需要2023年3月以后发布的版本，之前的目前无法破解

Hello，
4、UnityCrackTool为Win和Mac的破解工具,适用于2023年3月之前发布的版本。
是只有CN版是3月后，国际版3月前的意思吗？😂

**Comment by YueWangChen** [comment]
稍等 今天会把每个文件夹都添加上说明

**Comment by mGameStudio** [comment]
@YueWangChen 兄弟，牛逼！吓到我了，下载下来2.28个G，什么都包含了！一句话，把大家都整不会了。

专业！这就是专业~！

**Comment by agentbillwh** [comment]
Try this patch: https://github.com/agentbillwh/unilic

**Comment by JianjianGit** [comment]
2022.3 lts都出来了，啥时候支持一下

**Comment by WoolBRKIN** [comment]
> 



> ![20230606164134](https://user-images.githubusercontent.com/16739213/243639262-ab611844-7a7f-4f76-b29f-584385beac08.png)
> 
> 用楼上大佬的[Uni-HubHacker](https://github.com/YueWangChen/Uni-HubHacker)确实有效。但是那老哥提供的各个版本文件太多了，实际上只需要3个对应版本的文件, 需手动操作。他的破解思路跟UniHacker不同，改的是License验证工具里的System.Security.Cryptography.Xml.dll，没动Unity.exe. 如果UniHacker作者借鉴一下思路做成自动化就完美了



> ![20230606164134](https://user-images.githubusercontent.com/16739213/243639262-ab611844-7a7f-4f76-b29f-584385beac08.png)
> 
> 用楼上大佬的[Uni-HubHacker](https://github.com/YueWangChen/Uni-HubHacker)确实有效。但是那老哥提供的各个版本文件太多了，实际上只需要3个对应版本的文件, 需手动操作。他的破解思路跟UniHacker不同，改的是License验证工具里的System.Security.Cryptography.Xml.dll，没动Unity.exe. 如果UniHacker作者借鉴一下思路做成自动化就完美了

你好，个人在家里用的话会有封号风险吗

**Comment by sunsvip** [comment]
> 

我没登录UnityHub，破解后正常使用

**Comment by Soneoylys** [comment]
Issue关闭, 需要重构license inject方案
Refer to #198

**Comment by takineko-tfs** [comment]
Can someone upload `C:\ProgramData\Unity\Unity_lic.ulf` for Unity 2022 and later?

**Comment by hackeranmol** [comment]
@YueWangChen 

https://github.com/YueWangChen/Uni-HubHacker

Why page delete ? 

We need you brother ?

**Comment by JianjianGit** [comment]
健健已收到你的邮件

**Comment by guolijun110** [comment]
求2022.3的方法

**Comment by shaoy1234567** [comment]
https://github.com/parhelia512/Uni-HubHacker

**Comment by soft2005168** [comment]
@YueWangChen,你在哪里呢，页面怎么找不见了

**Comment by jiakuaibu** [comment]
> https://github.com/parhelia512/Uni-HubHacker

not working for me. i tried unity 2022.3.5 and 2022.3.8, none of them works.

**Comment by gbgabyte** [comment]
有最新的破解进展吗？

**Comment by JianjianGit** [comment]
健健已收到你的邮件
