### ISSUE TITLE
Unity 2021.2.0b11 PS 5 Support

### ISSUE THREAD

**Issue by Unagaml** [tylearymf/UniHacker#79]
Hello, I used a unityhacker last version on the unity, but for some reason the tab with PS 5 remained like this:
![screenshoot](https://user-images.githubusercontent.com/92244180/197278095-4dfdc90d-e977-4e04-9ae1-94c2817b7d84.png)

**Comment by tylearymf** [comment]
[UniHacker-win-x64V3.8.2.zip](https://github.com/tylearymf/UniHacker/files/9843392/UniHacker-win-x64V3.8.2.zip)
@Unagaml Try this version, execute REVERT first, then execute PATCH

**Comment by Unagaml** [comment]
Working! Thankyou!
![ok](https://user-images.githubusercontent.com/92244180/197333116-7dd56de9-7220-4422-afb8-1be32469ecbe.png)
