### ISSUE TITLE
not works on macOS Ventura

### ISSUE THREAD

**Issue by aminvio** [tylearymf/UniHacker#80]
i was successfully run 3.8 version on mac m1, but today i update my system to last version (macOS Ventura) and i lost my unity hub, it says this app is damaged and i should move it to trash, my unity (was cracked on pervious mac version) is still working, but i can't open UniHacker anymore ...
after opening app and entering my password, immediately it shows "task completed" without opening the app.

**Comment by aminvio** [comment]
I don't think it has any effect
maybe you need to change some stuff to work on new mac version

**Comment by aminvio** [comment]
like SDK or something ..

**Comment by tylearymf** [comment]
@aminvio , It works fine on ventura beta on the virtual machine.
![image](https://user-images.githubusercontent.com/14980389/198252949-6aa1830d-c84e-4fd0-96e6-e71a056da6ce.png)

**Comment by aminvio** [comment]
it works but when i patch unity hub (last version) it says: "“Unity Hub” is damaged and can’t be opened. You should move it to the Trash."

**Comment by tylearymf** [comment]
> it works but when i patch unity hub (last version) it says: "“Unity Hub” is damaged and can’t be opened. You should move it to the Trash."

You can try to reinstall it.

**Comment by aminvio** [comment]
it has not any effects ..

**Comment by XINCGer** [comment]
look at this link:https://zhuanlan.zhihu.com/p/577815562

**Comment by parkycai** [comment]
看起来是 xattr remove quanrantine失效了，等有空了看看咋回事

[https://www.reddit.com/r/MacOS/comments/yiow98/remove_quarantine_under_ventura/](https://www.reddit.com/r/MacOS/comments/yiow98/remove_quarantine_under_ventura/)

**Comment by tylearymf** [comment]
@parkycai 话说你之前提pr时的名字还是邮箱有问题，导致github没识别到你是contributor之一😂😂

**Comment by parkycai** [comment]
我是透明小菜鸡😏
