### ISSUE TITLE
2022.1.21和2021.3.12不支持

### ISSUE THREAD

**Issue by Honlay** [tylearymf/UniHacker#82]
![31667479486_ pic](https://user-images.githubusercontent.com/46173746/199724441-d272bb73-acc8-4c00-9a0e-d0e02f8b9b6c.jpg)
![51667479552_ pic](https://user-images.githubusercontent.com/46173746/199724465-3b457748-2c83-4e19-9bff-2f460afdde9b.jpg)

**Comment by Honlay** [comment]
链接: https://pan.baidu.com/s/1y1I6efCW-3ETmHJcSOrDkw 提取码: uogh 
--来自百度网盘超级会员v5的分享
 
谢谢大神, 2021.3.12好像是支持的,但是破解一次之后再次打开之后又提示不支持了,破解之后unity非常卡顿,不知道是不是破解的问题,别的版本不卡

**Comment by Honlay** [comment]
> @Honlay 提供下这两个版本的'Unity'二进制文件
> 
> ```
> Unity.app/Contents/MacOS/Unity
> ```

链接: https://pan.baidu.com/s/1y1I6efCW-3ETmHJcSOrDkw 提取码: uogh
--来自百度网盘超级会员v5的分享

谢谢大神, 2021.3.12好像是支持的,但是破解一次之后再次打开之后又提示不支持了,破解之后unity非常卡顿,不知道是不是破解的问题,别的版本不卡

**Comment by tylearymf** [comment]
@Honlay 用4.0版试下，卡顿不清楚你那边是啥情况

**Comment by Honlay** [comment]
> @Honlay 用4.0版试下，卡顿不清楚你那边是啥情况

成功了
