### ISSUE TITLE
2019.4.35f1  不能破解

### ISSUE THREAD

**Issue by codezjg** [tylearymf/UniHacker#83]
如题,在macos上不能破解2019.4.35f1 
![WX20221104-140508@2x](https://user-images.githubusercontent.com/1821421/199903185-bb0c99f1-eff9-456f-a445-c55099f85b83.png)

**Comment by tylearymf** [comment]
@codezjg 提供下Unity二进制文件，在这里：Unity.app/Contents/MacOS/Unity

**Comment by codezjg** [comment]
二进制文件下载地址
链接: https://pan.baidu.com/s/17qzbhU5rfiaske3i7_sPuw?pwd=ppiu 提取码: ppiu

**Comment by tylearymf** [comment]
@codezjg 试下 https://wwt.lanzouv.com/ibTHG0f6n56b

**Comment by codezjg** [comment]
好像还是不行.
<img width="520" alt="image" src="https://user-images.githubusercontent.com/1821421/199906843-b024aa8a-d75c-473a-ab0e-0f6e1bba7f98.png">

**Comment by tylearymf** [comment]
> 好像还是不行. <img alt="image" width="520" src="https://user-images.githubusercontent.com/1821421/199906843-b024aa8a-d75c-473a-ab0e-0f6e1bba7f98.png">

那我晚点再看看

**Comment by codezjg** [comment]
恩恩,麻烦大佬了
字节小游戏,必须要使用这个版本,不然我都不想弄它了,

**Comment by tylearymf** [comment]
> 恩恩,麻烦大佬了 字节小游戏,必须要使用这个版本,不然我都不想弄它了,

https://wwt.lanzouv.com/ipjx70f6xceb 再试下

**Comment by codezjg** [comment]
@tylearymf  大佬威武!  成功了

**Comment by codezjg** [comment]
我觉得大佬可以弄一个二维码,开通打赏

**Comment by tylearymf** [comment]
> 我觉得大佬可以弄一个二维码,开通打赏

不用，这个也是搞着玩玩的🤣

**Comment by codezjg** [comment]
👍🏻👍🏻👍🏻👍🏻👍🏻
