### ISSUE TITLE
请问有考虑出一个控制台的版本么

### ISSUE THREAD

**Issue by coding2233** [tylearymf/UniHacker#86]

**Comment by tylearymf** [comment]
是想docker跑吗还是只是单纯控制台，用途在哪呢

**Comment by coding2233** [comment]
想跑docker ， 自建的CI/CD，方便打包测试

**Comment by tylearymf** [comment]
> 想跑docker ， 自建的CI/CD，方便打包测试

有空我研究下

**Comment by coding2233** [comment]
> 

好的，感谢

**Comment by parkycai** [comment]
跑CI只要准备好已破解的Unity，覆盖一下好了哇

**Comment by tylearymf** [comment]
@coding2233 试下 https://github.com/tylearymf/unihacker-docker

**Comment by tylearymf** [comment]
https://hub.docker.com/r/tylearymf/unihacker

**Comment by coding2233** [comment]
![2022-11-13 141948](https://user-images.githubusercontent.com/20962849/201509971-1e9113b0-8fa5-4bc1-b98d-2a46cba6997d.jpg)
![2022-11-13 142023](https://user-images.githubusercontent.com/20962849/201509976-9ef85d4c-eba8-4b6a-96fc-be41593b703a.jpg)
已测试, 完美运行

**Comment by tylearymf** [comment]
@coding2233 之前的文档里的方式有问题，如果再创建个unity或hub容器会覆盖掉上次已安装的，导致上次安装的容器不能正常运行，新的方式已经写在文档里了，可以按照新方式操作下
