### ISSUE TITLE
2020.3.41f1 not support

### ISSUE THREAD

**Issue by hakadao-max** [tylearymf/UniHacker#88]

**Comment by tylearymf** [comment]
@hakadao-max 执行下还原、再破解试试

**Comment by hakadao-max** [comment]
> @hakadao-max 执行下还原、再破解试试

我试了几次，还是会这样

**Comment by tylearymf** [comment]
你是不是hub没破解

**Comment by hakadao-max** [comment]
> 你是不是hub没破解

破解了，用了19,21的破解有段时间了，刚下的20.3.41，然后进不去

**Comment by tylearymf** [comment]
hub也执行下还原，再破解试试？

**Comment by hakadao-max** [comment]
> hub也执行下还原，再破解试试？

可以了，感谢

**Comment by tylearymf** [comment]
> > hub也执行下还原，再破解试试？
> 
> 可以了，感谢

可能是你之前的hub破解后，又更新了

**Comment by hakadao-max** [comment]
> > > hub也执行下还原，再破解试试？
> > 
> > 
> > 可以了，感谢
> 
> 可能是你之前的hub破解后，又更新了

嗯，应该不会自己更新，我看版本一直是3.1.1，刚才也是其他之间之前破解的版本可以开，只有3.41不行
