### ISSUE TITLE
2019.4.10f1 (mac) 不支持

### ISSUE THREAD

**Issue by tkgamegroup** [tylearymf/UniHacker#89]
下载的国际版
![截屏2022-11-16 23 13 20](https://user-images.githubusercontent.com/12348900/202380467-58ac164b-82d7-417f-8515-0f9bb8ebd08a.png)

**Comment by tylearymf** [comment]
@tkgamegroup 提供下Unity二进制文件

**Comment by tkgamegroup** [comment]
https://share.weiyun.com/01WBxFdE

**Comment by tylearymf** [comment]
> https://share.weiyun.com/01WBxFdE

试下
https://wwt.lanzouv.com/iizq50g54xmb
密码:dck5

**Comment by tkgamegroup** [comment]
可以了QAQ
大佬太牛了...这么快就搞定了...受我一拜
