### ISSUE TITLE
2022.1.23f1 (Linux) 2022.1.23f1.git.9844400 (X64)

### ISSUE THREAD

**Issue by reidsneo** [tylearymf/UniHacker#90]
![image](https://user-images.githubusercontent.com/12298979/202697613-9f1fb377-ce7b-45f8-872b-3cd51630bc36.png)

Any chance for the latest linux version?
https://www91.zippyshare.com/v/6ENiGDfs/file.html

Thanks!

**Comment by tylearymf** [comment]
@reidsneo Try new version. https://github.com/tylearymf/UniHacker/releases/tag/4.1

**Comment by reidsneo** [comment]
![image](https://user-images.githubusercontent.com/12298979/202728666-9b862784-b12a-4562-a4c5-814365847a57.png)

Thank you for the quick response!
you are the best
*case closed*
