### ISSUE TITLE
希望能支持一下2019.3.4f1版本，非常感谢

### ISSUE THREAD

**Issue by snowynight2022** [tylearymf/UniHacker#92]

**Comment by tylearymf** [comment]
提供下unity二进制文件

**Comment by snowynight2022** [comment]
[Unity.zip](https://github.com/tylearymf/UniHacker/files/10073278/Unity.zip) mac版本的

**Comment by tylearymf** [comment]
> [Unity.zip](https://github.com/tylearymf/UniHacker/files/10073278/Unity.zip) mac版本的

你这个文件只有1kb

**Comment by tylearymf** [comment]
@snowynight2022 试下
https://wwt.lanzouv.com/imPd90gpsoze
密码:3fs3

**Comment by snowynight2022** [comment]
![unity](https://user-images.githubusercontent.com/44424722/203691028-de2b5138-4cd3-424a-8652-9c1858fab389.png)
可以用，非常感谢！！！
