### ISSUE TITLE
希望支持unity2019.4.40 mac版本

### ISSUE THREAD

**Issue by cl535657573** [tylearymf/UniHacker#93]
希望支持unity2019.4.40 mac版本

**Comment by tylearymf** [comment]
> 希望支持unity2019.4.40 mac版本

这个版本是支持的，你可能下载的不是国际版

**Comment by fgfg54321** [comment]
我确定下载的是unity2019.4.40 mac国际版本 但是也提示不支持破解

**Comment by fgfg54321** [comment]
我发现我在旧的版本 3.8上可以支持破解  并且成功了 新的版本4.1上不行

**Comment by tylearymf** [comment]
> 我发现我在旧的版本 3.8上可以支持破解 并且成功了 新的版本4.1上不行

@fgfg54321 @cl535657573 🤣查了下是因为之前整合了不同版本下的补丁，现在还原回去了，重新上传到[release 4.1](https://github.com/tylearymf/UniHacker/releases/tag/4.1)里了，再下载试试
