### ISSUE TITLE
希望支持一下 2018.4.30f1

### ISSUE THREAD

**Issue by coder-free** [tylearymf/UniHacker#94]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/2630290/203752531-0dc76ba9-8204-444f-a538-5c24bcb69e69.png">

<img width="520" alt="image" src="https://user-images.githubusercontent.com/2630290/203752334-458c0330-1c25-4d86-8f1e-7c9ec32d8827.png">

**Comment by coder-free** [comment]
压缩完还有四十多兆，传不上来，我也没啥地方放，我传到百度网盘去了

链接: https://pan.baidu.com/s/1LzRt0X9altrToeT6QuZ3ug?pwd=8hut 
提取码: 8hut 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by coder-free** [comment]
刚想起来还能发邮件，给您发了个邮件，附件里面也是这个 压缩包

**Comment by tylearymf** [comment]
> 刚想起来还能发邮件，给您发了个邮件，附件里面也是这个 压缩包

我刚下了网盘的

**Comment by tylearymf** [comment]
@coder-free 你的是国内版本的，去这里下国际版的
Github 国际版下载地址：https://github.com/AlianBlank/download.unity.com

**Comment by coder-free** [comment]
@tylearymf ok，谢谢
