### ISSUE TITLE
账户登录问题

### ISSUE THREAD

**Issue by wypicc** [tylearymf/UniHacker#96]
使用后，没法登录unity账户，点击登录后跳转到浏览器登录，然后就没有然后了。。。
网页停留在https://api.unity.cn/v1/oauth2/authoriz巴拉巴拉
没有唤醒unityhub

**Comment by tylearymf** [comment]
> 使用后，没法登录unity账户，点击登录后跳转到浏览器登录，然后就没有然后了。。。 网页停留在[https://api.unity.cn/v1/oauth2/authoriz巴拉巴拉](https://api.unity.cn/v1/oauth2/authoriz%E5%B7%B4%E6%8B%89%E5%B7%B4%E6%8B%89) 没有唤醒unityhub

![image](https://user-images.githubusercontent.com/14980389/204701862-d8f94272-c896-42d4-b734-b02a512b8d7b.png)
