### ISSUE TITLE
以不登录自己账户的选项破解后无法新建项目

### ISSUE THREAD

**Issue by L2750558108** [tylearymf/UniHacker#98]
我用unihacker破解了unityHub 3.3，选择不登录自己的账户，然后新建项目时看不到版本控制的复选框。点确定后要求我下载PlasticSCM。下载之后又要求我登录后继续，但这不是无需登录的版本吗。我觉得应该能够不选择启用版本控制或者在启用版本控制时不登录。

**Comment by tylearymf** [comment]
破解Hub时，选不登录自己的账户，只提供了最基础的功能：打开Unity工程。
如果你需要用到版本控制，就必须选登录自己的账号。

**Comment by L2750558108** [comment]
> 破解Hub时，选不登录自己的账户，只提供了最基础的功能：打开Unity工程。 如果你需要用到版本控制，就必须选登录自己的账号。

但是这导致无法创建项目，即便不使用版本控制

**Comment by tylearymf** [comment]
> > 破解Hub时，选不登录自己的账户，只提供了最基础的功能：打开Unity工程。 如果你需要用到版本控制，就必须选登录自己的账号。
> 
> 但是这导致无法创建项目，即便不使用版本控制

你可能环境有问题，正常破解完是可以创建项目的。
你可以执行下以下步骤：
1. 打开UniHacker，选择 Hub.exe
2. 点击 “破解” 按钮下面的 “还原” 按钮
3. 再次点击 “破解” 按钮
